### ISSUE TITLE
Install fails with unicode error

### ISSUE THREAD

**Issue by YannBrrd** [jupyter/jupyterhub#127]
Hi,

I'm trying to build a Dockerfile with [Anaconda-Python 3.4](http://continuum.io/downloads#py34) & Jupyterhub, but when running
```pip install .```
I get this stack error : 
```python
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/opt/anaconda/lib/python3.4/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/opt/anaconda/lib/python3.4/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/opt/anaconda/lib/python3.4/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/opt/anaconda/lib/python3.4/site-packages/pip/util.py", line 681, in call_subprocess
    logger.log(level, line)
  File "/opt/anaconda/lib/python3.4/site-packages/pip/log.py", line 162, in log
    consumer.write(write_content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-6: ordinal not in range(128)

Storing debug log for failure in /root/.pip/pip.log
```

Dockerfile : 
```
FROM debian:8
MAINTAINER Yann Barraud "yann.barraud@gmail.com"

#Installing dependencies

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install apt-utils -y
RUN apt-get upgrade -y
# For Anaconda installer
RUN apt-get install bzip2 -y
#For Jupyter
RUN apt-get install npm nodejs-legacy git -y
RUN apt-get autoremove -y && apt-get clean -y

# Uploading Anaconda installer
ADD src /root

# Installing Anaconda
WORKDIR /root

RUN ["bash", "/root/Anaconda3-2.1.0-Linux-x86_64.sh", "-b", "-p", "/opt/anaconda"]
RUN ["rm", "/root/Anaconda3-2.1.0-Linux-x86_64.sh"]

# Updating PATH
ENV PATH /opt/anaconda/bin:$PATH

# Installing Jupyter

RUN ["npm", "install", "-g", "bower", "less", "jupyter/configurable-http-proxy"]

#Cloning JupyterHub
RUN ["git", "clone", "https://github.com/jupyter/jupyterhub.git"]
WORKDIR /root/jupyterhub
RUN ["pip", "install", "-r", "requirements.txt"]
RUN ["pip" ,"install", "."]


#EXPOSE 8000
#RUN jupyterhub
``` 

Anything I should fix ? 

Thanks.

Yann

**Comment by dsblank** [comment]
You might try updating pip:

```
sudo pip install pip -U
```

**Comment by YannBrrd** [comment]
Cool, having the thig running :) Thanks
