### ISSUE TITLE
Sudospawner failing

### ISSUE THREAD

**Issue by tantczak** [jupyter/jupyterhub#155]
Hi,

So I've read through the issues and seen stuff similar to what I'm seeing, but not exactly the same.  When I run Jupyterhub without sudospawner, as root, it works fine. When I run it with sudospawner, EVEN AS ROOT, it fails.  Here's my command line and the stack trace of the failure:

```
[root@research01 jupyter]# jupyterhub --config=/usr/local/lib/python3.4/site-packages/jupyterhub/jupyterhub_config.py 
[I 2015-02-26 17:12:52.828 JupyterHub app:453] Loading cookie_secret from /etc/jupyter/jupyterhub_cookie_secret
[W 2015-02-26 17:12:52.860 JupyterHub app:240] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-02-26 17:12:52.868 JupyterHub app:546] Not using whitelist. Any authenticated user will be allowed.
[I 2015-02-26 17:12:52.882 JupyterHub app:678] Starting proxy @ http://*:8000/
17:12:53.024 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
17:12:53.028 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
sudo: sudospawner: command not found
[E 2015-02-26 17:13:08.772 JupyterHub orm:353] Unhandled error starting tantczak's server: Expecting value: line 1 column 1 (char 0)
[E 2015-02-26 17:13:08.776 JupyterHub web:1421] Uncaught exception GET /hub/user/tantczak/ (10.1.22.130)
    HTTPServerRequest(protocol='http', host='research01:8000', method='GET', uri='/hub/user/tantczak/', version='HTTP/1.1', remote_ip='10.1.22.130', headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0', 'Accept-Language': 'en-US,en;q=0.5', 'X-Forwarded-For': '10.1.22.130', 'Referer': 'http://research01:8000/hub/home', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Proto': 'http', 'Host': 'research01:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Cookie': 'jupyter-hub-token="2|1:0|10:1424447096|17:jupyter-hub-token|44:NjRjNmQzYTA3MjAxNGI1YzllMzllYzIyNDc4OWFkMjQ=|7a6926c8c9e555ddf12c41dc1541e518594e55aa51d37c1d2cc9d26a5c951927"', 'Connection': 'close', 'X-Forwarded-Port': '8000'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 1348, in _execute
        result = yield result
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 373, in get
        yield self.spawn_single_user(current_user)
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 214, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 812, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/orm.py", line 362, in spawn
        raise e
      File "/usr/local/lib/python3.4/site-packages/jupyterhub/orm.py", line 345, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python3.4/site-packages/sudospawner/spawner.py", line 52, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.env)
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python3.4/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/site-packages/tornado/gen.py", line 812, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python3.4/site-packages/sudospawner/spawner.py", line 46, in do
        return json.loads(data.decode('utf8'))
      File "/usr/local/lib/python3.4/json/__init__.py", line 318, in loads
        return _default_decoder.decode(s)
      File "/usr/local/lib/python3.4/json/decoder.py", line 343, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/lib/python3.4/json/decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)
[E 2015-02-26 17:13:08.836 JupyterHub web:1825] 500 GET /hub/user/tantczak/ (10.1.22.130) 99.55ms
[I 2015-02-26 17:13:09.401 JupyterHub web:1825] 304 GET /hub/static/components/requirejs/require.js?v=4805364156371be297aa5ab7f8b204cb (10.1.22.130) 8.30ms
[I 2015-02-26 17:13:09.403 JupyterHub web:1825] 200 GET /hub/static/css/style.min.css?v=2537bbc7ee84eeba39e7e3f855f9b1df (10.1.22.130) 1.16ms
[I 2015-02-26 17:13:09.766 JupyterHub web:1825] 304 GET /hub/static/images/jupyterhub-80.png?v=f2425886998fa90d2abfe69770803e7c (10.1.22.130) 0.74ms
[I 2015-02-26 17:13:10.234 JupyterHub web:1825] 200 GET /favicon.ico (10.1.22.130) 0.86ms
^C
Interrupted
[I 2015-02-26 17:17:37.212 JupyterHub app:800] Cleaning up single-user servers...
[I 2015-02-26 17:17:37.217 JupyterHub app:829] ...done
```

AS you can see, rather than explicitly calling out sudospawner on the jupyterhib command line, I'm using a config file.  Here's the relevant line from that:

c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'

Any idea what's going on here?

**Comment by minrk** [comment]
Can you run with `jupyterhub --debug` and add `SudoSpawner.debug_mediator = True` to your config?

**Comment by minrk** [comment]
Ah, this is probably the key:

> sudo: sudospawner: command not found

Did you install the sudpspawner? And if so, where?

**Comment by tantczak** [comment]
How did I miss that?  I must have looked through that output half a dozen times.  I did install sudospawener, using the instructions on the wiki and verified that it works:

[root@research01 ~]# which sudospawner
/usr/local/bin/sudospawner

There's gotta be some kind of pathing issue with sudo.  I'll investigate and let you know what i find out.  Thanks!

**Comment by tantczak** [comment]
That was the problem.  /usr/local/bin is in the path of the user I created to run this service, but not in that user's path when you switch to them via sudo.  I'm guess it's some sort of /etc/sudoers setting.  I linked /usr/local/bin/sudospawner to /usr/bin/sudospawner and this work as expected.  Thanks for the help and sorry for the dumb question.

**Comment by minrk** [comment]
Not a problem. I'm working on a few things that should reduce the noise surrounding the error, and make it a little easier to see next time.
