### ISSUE TITLE
No such file or directory: 'configurable-http-proxy'

### ISSUE THREAD

**Issue by astrofrog** [jupyter/jupyterhub#193]
I tried out jupyterhub 0.1 today and got the following exception:

```
[I 2015-03-17 13:10:37.737 JupyterHub app:509] Loading cookie_secret from /Volumes/Raptor/jupyterhub_cookie_secret
[W 2015-03-17 13:10:37.765 JupyterHub app:245] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-03-17 13:10:37.771 JupyterHub app:602] Not using whitelist. Any authenticated user will be allowed.
[I 2015-03-17 13:10:37.786 JupyterHub app:733] Starting proxy @ http://localhost:8000/
[C 2015-03-17 13:10:37.789 JupyterHub app:962] Failed to start proxy
    Traceback (most recent call last):
      File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/jupyterhub/app.py", line 960, in start
        yield self.start_proxy()
      File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/jupyterhub/app.py", line 735, in start_proxy
        self.proxy_process = Popen(cmd, env=env)
      File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'configurable-http-proxy'
```

Is this a known issue?

**Comment by astrofrog** [comment]
Oops, just saw it's a non-Python dependency hence why pip didn't install it :)

**Comment by minrk** [comment]
I should be able to make a better error, at least.

**Comment by astrofrog** [comment]
Thanks!
