### ISSUE TITLE
Installation failing on Ubuntu 14.04 with pip install .

### ISSUE THREAD

**Issue by fbrundu** [jupyter/jupyterhub#201]
Hi all,
I installed all the dependencies listed (I also have (i)python 3.4 installed). However, when I run `sudo pip install .` on `jupyterhub` cloned repository I get:

    /usr/local/bin/pip run on Thu Mar 19 10:41:28 2015
    Unpacking /home/francesco/git/jupyterhub
       Running setup.py (path:/tmp/pip-Co0pAS-build/setup.py) egg_info for package from file:///home/francesco/git/jupyterhub
         ERROR: Jupyter Hub requires Python version 3.3 or above.
         Complete output from command python setup.py egg_info:
         ERROR: Jupyter Hub requires Python version 3.3 or above.

    ----------------------------------------
    Cleaning up...
      Removing temporary dir /tmp/pip_build_root...
     Command python setup.py egg_info failed with error code 1 in /tmp/pip-Co0pAS-build
     Exception information:
     Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1229, in prepare_files
        req_to_install.run_egg_info()
      File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 325, in run_egg_info
        command_desc='python setup.py egg_info')
      File "/usr/local/lib/python2.7/dist-packages/pip/util.py", line 697, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-Co0pAS-build

Thanks

**Comment by dsblank** [comment]
You probably need to use pip3 to go with python3.

**Comment by fbrundu** [comment]
Yes, thanks. I tried to install it via

    sudo pip install --upgrade pip

and 

    sudo apt-get install python-pip3

But the correct command was

    sudo apt-get install python3-pip

Thank you

**Comment by KrishnaPG** [comment]
Faced the same problem. When run `sudo pip install .` got error saying "ERROR: Jupyter Hub requires Python version 3.3 or above."

Then did `sudo apt-get install python3-pip` as suggested above followed by `sudo pip3 install .` it went fine.

Perhaps the ReadMe.md should be updated. I would be happy to do PR if its ok.

**Comment by minrk** [comment]
@KrishnaPG that would be great, thanks!

**Comment by KrishnaPG** [comment]
Added the relevant details to `ReadMe.md` and created pull request https://github.com/jupyter/jupyterhub/pull/256

**Comment by dhaval1406** [comment]
I have followed steps from *https://github.com/jupyter/jupyterhub* and also tried above approaches but still failing on  *sudo pip3 install*, below is the error:

```
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-dsdgb5bx-build/setup.py", line 179, in run
        env=env,
      File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 1
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-dsdgb5bx-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f_u__rfn-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

running js

bower bootstrap#~3.1        not-cached git://github.com/components/bootstrap.git#~3.1

bower bootstrap#~3.1           resolve git://github.com/components/bootstrap.git#~3.1

bower font-awesome#~4.1     not-cached git://github.com/components/font-awesome.git#~4.1

bower font-awesome#~4.1        resolve git://github.com/components/font-awesome.git#~4.1

bower jquery#~2.0           not-cached git://github.com/components/jquery.git#~2.0

bower jquery#~2.0              resolve git://github.com/components/jquery.git#~2.0

bower moment#~2.7           not-cached git://github.com/moment/moment.git#~2.7

bower moment#~2.7              resolve git://github.com/moment/moment.git#~2.7

bower requirejs#~2.1        not-cached git://github.com/jrburke/requirejs-bower.git#~2.1

bower requirejs#~2.1           resolve git://github.com/jrburke/requirejs-bower.git#~2.1

bower moment#~2.7              ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/moment/moment.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Connection timed out



Additional error details:

fatal: unable to connect to github.com:

github.com[0: 192.30.252.130]: errno=Connection timed out

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-dsdgb5bx-build/setup.py", line 297, in <module>

    main()

  File "/tmp/pip-dsdgb5bx-build/setup.py", line 294, in main

    setup(**setup_args)

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python3.4/distutils/command/install.py", line 598, in run

    self.run_command('build')

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run

    self.run_command(cmd_name)

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/tmp/pip-dsdgb5bx-build/setup.py", line 249, in run

    self.run_command('js')

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/tmp/pip-dsdgb5bx-build/setup.py", line 179, in run

    env=env,

  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-dsdgb5bx-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f_u__rfn-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-dsdgb5bx-build
Storing debug log for failure in /home/rwdna/.pip/pip.log
```

Below errors are from *pip.log* file

```----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-dsdgb5bx-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f_u__rfn-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-dsdgb5bx-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-dsdgb5bx-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-f_u__rfn-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-dsdgb5bx-build
```

**Comment by KrishnaPG** [comment]
This is some network error you are getting. Note the `fatal: unable to connect to github.com:` in your error log which is the problem.

This command `git ls-remote --tags --heads git://github.com/moment/moment.git` is not getting executed properly. 

Please check why git is unable to connect. For example, try running that above command manually and see if that works fine.

**Comment by dhaval1406** [comment]
Thanks @KrishnaPG . I figured out the issue, I think it was my firewall that was blocking ```git://```. When I changed my settings to use ```https://..``` instead, it went smoothly.

Below is the command I used to make this config change in case someone experience this issue:

```git config --global url."https://".insteadOf git://```
