### ISSUE TITLE
Server slow to start then 500 server error (sudo spawner)

### ISSUE THREAD

**Issue by YannBrrd** [jupyter/jupyterhub#206]
Hi,

I'm going on with sudospawner and jupyterhub, but still facing issues... :-(

```
[W 2015-03-23 10:28:33.180 JupyterHub base:218] User joe server is slow to start
[W 2015-03-23 10:28:53.523 JupyterHub orm:378] joe's server never showed up at http://localhost:43084/user/joe after 30 seconds. Giving up
[I 150323 10:28:54 mediator:62] Spawning /opt/anaconda3/bin/python3 -m jupyterhub.singleuser --user=joe --port=43236 --cookie-name=jupyter-hub-token-joe --base-url=/user/joe --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost '--notebook-dir=~/notebooks/'
[W 2015-03-23 10:29:03.859 JupyterHub base:218] User joe server is slow to start
[W 2015-03-23 10:29:24.185 JupyterHub orm:378] joe's server never showed up at http://localhost:43236/user/joe after 30 seconds. Giving up
[I 150323 10:29:24 mediator:62] Spawning /opt/anaconda3/bin/python3 -m jupyterhub.singleuser --user=joe --port=36984 --cookie-name=jupyter-hub-token-joe --base-url=/user/joe --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost '--notebook-dir=~/notebooks/'
[E 2015-03-23 10:29:24.786 JupyterHub web:1407] Uncaught exception GET /hub/user/joe/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/hub/user/joe/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'If-None-Match': '"fad16be26c68ce12713f9bfb3b1fd71c7c5410ed"', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.5', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Cache-Control': 'max-age=0', 'Host': 'localhost:8081', 'Connection': 'keep-alive', 'Cookie': 'jupyter-hub-token="2|1:0|10:1427102774|17:jupyter-hub-token|44:YWZhMTBhMzk4OGQ0NGQ4Mzg4NDI1YjU4MjAwZWM0NWM=|67dc74b930f36339dda60f420d28fdf2087121c98afffe77deb9de97716293c7"', 'Referer': 'http://localhost:8081/hub/home'})
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.4/site-packages/tornado/web.py", line 1334, in _execute
        result = yield result
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 371, in get
        yield self.spawn_single_user(current_user)
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 214, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/orm.py", line 383, in spawn
        user=self.name, url=self.server.url, error=e,
    AttributeError: 'NoneType' object has no attribute 'url'
    
[E 2015-03-23 10:29:24.804 JupyterHub web:1811] 500 GET /hub/user/joe/ (127.0.0.1) 361.40ms
´´´

Any tip/help/idea ? 

Thanks.

**Comment by YannBrrd** [comment]
In fact looks like the process is never launched. When I try to put logs in mediator.py (spawn methods), looks like I pass through the fork then the close options, but within the close, does not lead anywhere...

**Comment by minrk** [comment]
Can you verify that the process is never started? That would be very surprising. Maybe it's starting and dying immediately?

**Comment by YannBrrd** [comment]
Hi,

How would you do that ? Any trace somewhere ? Or just regular ps ?


Cordialement,
Yann Barraud

2015-03-23 19:13 GMT+01:00 Min RK <notifications@github.com>:

**Comment by minrk** [comment]
If you instrument (fancy word for print statement or debugger breakpoint) `mediator.py`, you can check out the pid of the Popen instance. If something's hanging on the way there, you can locate what call is blocking.

**Comment by YannBrrd** [comment]
I tried to add some logs in mediator.py but never reached the code I put...


Cordialement,
Yann Barraud

2015-03-23 19:40 GMT+01:00 Min RK <notifications@github.com>:

**Comment by minrk** [comment]
Can you identify the last statement that executes on the child (the `else` block after fork)?

**Comment by YannBrrd** [comment]
```python
for fp in [sys.stdin, sys.stdout, sys.stderr]:
            os.dup2(null, fp.fileno())
```

Not getting out of the loop. 2 iterations and then nothing...

**Comment by minrk** [comment]
Okay, I'll see what I can dig up. What distro, version, etc.? How stock is the system?

**Comment by YannBrrd** [comment]
It's a Linux Mint 17.1 on VM... (x64)

**Comment by minrk** [comment]
I set up a new Mint 17.1 (x64) VM, and went through the following steps:

install everything:

    sudo apt-get -y update
    sudo apt-get -y install git libzmq3-dev build-essential python3-dev python3-pip npm nodejs-legacy
    sudo npm install -g configurable-http-proxy
    sudo pip3 install -e git+https://github.com/jupyter/jupyterhub#egg=jupyterhub
    sudo pip3 install -e git+https://github.com/jupyter/sudospawner#egg=sudospawner

add rhea user, with PAM permissions:

    sudo useradd rhea
    sudo usermod -a -G shadow rhea

grant `rhea` access to `sudospawner` in `/etc/sudoers`:

    Runas_Alias JUPYTER_USERS = user1, user2
    Cmnd_Alias JUPYTER_CMD = /usr/local/bin/sudospawner
    rhea ALL=(JUPYTER_USERS) NOPASSWD:JUPYTER_CMD

Make jupyterhub dir, owned by rhea:

     sudo mkdir /etc/jupyterhub
     sudo chown rhea /etc/jupyterhub

Run JupyterHub:

    cd /etc/jupyterhub
    sudo -u rhea jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner

At this point, logging in and running code works as user1 or user2.

So I still don't know what could be going wrong, but at least a simple setup with no other interactions does work.

**Comment by YannBrrd** [comment]
Mmmm... Thanks.
Will try to setup all again.
Can you try with anaconda installed in /opt/anaconda3 ?

**Comment by peterruppel** [comment]
Hi,
I am having the exact same issue with Ubuntu 14.04. Following the instruction from @minrk above, I just installed everything from scratch in a new VM, but still get a timeout error - see below.

```
rhea@instance-1:/etc/jupyterhub$ jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner
[I 2015-03-25 12:23:36.326 JupyterHub app:514] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[W 2015-03-25 12:23:36.345 JupyterHub app:250] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-03-25 12:23:36.350 JupyterHub app:607] Not using whitelist. Any authenticated user will be allowed.
[I 2015-03-25 12:23:36.360 JupyterHub app:738] Starting proxy @ http://*:8000/
12:23:36.570 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
12:23:36.573 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-03-25 12:23:36.631 JupyterHub app:1002] Hub API listening on http://localhost:8081/hub/
[I 2015-03-25 12:26:38.255 JupyterHub log:100] 302 GET / (@127.0.0.1) 1.38ms
[I 2015-03-25 12:26:38.257 JupyterHub log:100] 302 GET /hub (@127.0.0.1) 0.30ms
[I 2015-03-25 12:26:38.291 JupyterHub log:100] 200 GET /hub/ (@127.0.0.1) 30.22ms
[I 2015-03-25 12:32:04.448 JupyterHub log:100] 302 GET / (@XXX.XXX.XXX.XXX) 3.77ms
[I 2015-03-25 12:32:04.477 JupyterHub log:100] 302 GET /hub (@XXX.XXX.XXX.XXX) 0.81ms
[I 2015-03-25 12:32:04.511 JupyterHub log:100] 200 GET /hub/ (@XXX.XXX.XXX.XXX) 1.34ms
[I 2015-03-25 12:32:06.675 JupyterHub log:100] 200 GET /hub/login (@XXX.XXX.XXX.XXX) 6.20ms
[I 150325 12:32:11 mediator:62] Spawning /usr/bin/python3 -m jupyterhub.singleuser --user=user1 --port=60122 --cook
ie-name=jupyter-hub-token-user1 --base-url=/user/user1 --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/a
pi --ip=localhost
[W 2015-03-25 12:32:21.512 JupyterHub base:238] User user1 server is slow to start
[I 2015-03-25 12:32:21.519 JupyterHub log:100] 302 POST /hub/login?next= (@XXX.XXX.XXX.XXX) 10115.86ms
[I 2015-03-25 12:32:21.557 JupyterHub log:100] 302 GET /hub/ (user1@XXX.XXX.XXX.XXX) 2.49ms
[I 2015-03-25 12:32:21.599 JupyterHub log:100] 200 GET /hub/home (user1@XXX.XXX.XXX.XXX) 7.84ms
[W 2015-03-25 12:32:42.276 JupyterHub orm:395] user1's server never showed up at http://localhost:60122/user/user1 
after 30 seconds. Giving up
[E 2015-03-25 12:32:43.103 JupyterHub gen:673] Exception in Future <tornado.concurrent.Future object at 0x7f851e97c
048> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 669, in error_callback
        future.result()
      File "/home/XXX/src/jupyterhub/jupyterhub/orm.py", line 411, in spawn
        raise e
      File "/home/XXX/src/jupyterhub/jupyterhub/orm.py", line 387, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/home/XXX/src/jupyterhub/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/home/XXX/src/jupyterhub/jupyterhub/utils.py", line 83, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:60122/user/user1 didn't respond in 30 seconds
```

**Comment by YannBrrd** [comment]
Same here. Got rid of anaconda3 this time, and getting the exact same result as peter... :/

**Comment by minrk** [comment]
These are on new VMs?

**Comment by peterruppel** [comment]
Yes, new VM (Ubuntu 14.04 on Google Compute Engine).
I just got it working after manually installing
```
sudo pip3 install pyzmq
sudo pip3 install jsonschema
sudo pip3 install terminado
```
in addition to the steps decribed by @minrk above.
I got the error messages about the missing modules only after I removed `sys.stderr`from https://github.com/jupyter/sudospawner/blob/master/sudospawner/mediator.py#L83 (as @YannBrrd mentioned above, the process got caught after the second iteration).
Then, after installing the three modules and inserting the entry again in the for loop, everything works like a charm :-)

**Comment by minrk** [comment]
ok, sounds like the problem is really that stderr is getting hidden. I'll work on that.

**Comment by peterruppel** [comment]
Thanks!

**Comment by YannBrrd** [comment]
Too bad, I went a step further and now looping 302 
```bash
[I 2015-03-25 19:11:39.011 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.79ms
[I 2015-03-25 19:11:39.341 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 325.69ms
[I 2015-03-25 19:11:39.345 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.80ms
[I 2015-03-25 19:11:39.687 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 338.12ms
[I 2015-03-25 19:11:39.691 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 1.04ms
[I 2015-03-25 19:11:40.021 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 325.49ms
[I 2015-03-25 19:11:40.025 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.77ms
[I 2015-03-25 19:11:40.357 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 327.89ms
```

Will try investigate further...

**Comment by YannBrrd** [comment]
Any diea why the server would respond 302 ? 
```bash
[D 2015-03-27 11:55:02.760 JupyterHub spawner:219] Polling subprocess every 30s
[D 2015-03-27 11:55:03.279 JupyterHub utils:73] Server at http://localhost:36787/user/ybarraud responded with 302
[I 2015-03-27 11:55:03.280 JupyterHub base:229] User ybarraud server took 0.890 seconds to start
[I 2015-03-27 11:55:03.280 JupyterHub orm:169] Adding user ybarraud to proxy /user/ybarraud => http://localhost:36787
[D 2015-03-27 11:55:03.282 JupyterHub orm:156] Fetching POST http://localhost:8001/api/routes/user/ybarraud
11:55:03.286 - debug: [ConfigProxy] POST /user/ybarraud user=ybarraud, target=http://localhost:36787
[I 2015-03-27 11:55:03.291 JupyterHub log:100] 302 POST /hub/login?next= (@127.0.0.1) 920.03ms
[I 2015-03-27 11:55:03.297 JupyterHub log:100] 302 GET /hub/ (ybarraud@127.0.0.1) 2.20ms
```

**Comment by minrk** [comment]
That's typically a failure to authenticate.

**Comment by minrk** [comment]
If there's a problem with login cookies, it's possible to get a redirect loop as the single-user server fails to authenticate, redirects to the login page on the Hub, which *thinks* it's setting the correct login information and redirects back to the single-user server. Can you show more of the debug output when this is happening, starting from when the single-user server is started?

**Comment by YannBrrd** [comment]
Here it is (not much info though)

```bash
[I 150328 11:20:25 mediator:62] Spawning /opt/anaconda3/bin/python3 -m jupyterhub.singleuser --user=ybarraud --port=58933 --cookie-name=jupyter-hub-token-ybarraud --base-url=/user/ybarraud --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost '--notebook-dir=~/jupyter' --debug
[D 2015-03-28 11:20:25.428 JupyterHub spawner:219] Polling subprocess every 30s
[D 2015-03-28 11:20:25.952 JupyterHub utils:73] Server at http://localhost:58933/user/ybarraud responded with 302
[I 2015-03-28 11:20:25.953 JupyterHub base:229] User ybarraud server took 0.910 seconds to start
[I 2015-03-28 11:20:25.953 JupyterHub orm:169] Adding user ybarraud to proxy /user/ybarraud => http://localhost:58933
[D 2015-03-28 11:20:25.955 JupyterHub orm:156] Fetching POST http://localhost:8001/api/routes/user/ybarraud
11:20:25.958 - debug: [ConfigProxy] POST /user/ybarraud user=ybarraud, target=http://localhost:58933
[I 2015-03-28 11:20:25.965 JupyterHub log:100] 302 POST /hub/login?next= (@127.0.0.1) 939.53ms
[I 2015-03-28 11:20:25.972 JupyterHub log:100] 302 GET /hub/ (ybarraud@127.0.0.1) 2.08ms
[D 2015-03-28 11:20:25.984 JupyterHub log:100] 304 GET /hub/home (ybarraud@127.0.0.1) 8.17ms
[D 2015-03-28 11:20:26.046 JupyterHub log:100] 304 GET /hub/static/js/home.js (@127.0.0.1) 1.14ms
[D 2015-03-28 11:20:26.068 JupyterHub log:100] 304 GET /favicon.ico (@127.0.0.1) 0.46ms
[D 2015-03-28 11:20:26.069 JupyterHub log:100] 304 GET /hub/static/components/jquery/jquery.min.js (@127.0.0.1) 1.01ms
[D 2015-03-28 11:20:26.071 JupyterHub log:100] 304 GET /hub/static/js/jhapi.js (@127.0.0.1) 0.56ms
[D 2015-03-28 11:20:26.098 JupyterHub log:100] 304 GET /hub/static/js/utils.js (@127.0.0.1) 0.58ms
[I 2015-03-28 11:20:37.091 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 322.23ms
[I 2015-03-28 11:20:37.094 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.66ms
[I 2015-03-28 11:20:37.419 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 318.97ms
[I 2015-03-28 11:20:37.424 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 1.54ms
[I 2015-03-28 11:20:37.753 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 323.89ms
[I 2015-03-28 11:20:37.757 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.62ms
[I 2015-03-28 11:20:38.077 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 316.50ms
[I 2015-03-28 11:20:38.080 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.53ms
[I 2015-03-28 11:20:38.402 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 317.29ms
[I 2015-03-28 11:20:38.405 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.51ms
[I 2015-03-28 11:20:38.721 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 311.32ms
[I 2015-03-28 11:20:38.724 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.55ms
[I 2015-03-28 11:20:39.053 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 324.27ms
[I 2015-03-28 11:20:39.056 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.59ms
[I 2015-03-28 11:20:39.379 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 317.86ms
[I 2015-03-28 11:20:39.383 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.79ms
[I 2015-03-28 11:20:39.707 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 319.30ms
[I 2015-03-28 11:20:39.711 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.72ms
[I 2015-03-28 11:20:40.027 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 313.55ms
[I 2015-03-28 11:20:40.031 JupyterHub log:100] 302 GET /user/ybarraud/ (@127.0.0.1) 0.99ms
[I 2015-03-28 11:20:40.355 JupyterHub log:100] 302 GET /hub/user/ybarraud/ (ybarraud@127.0.0.1) 319.72ms
```

**Comment by minrk** [comment]
That looks like the single-user server isn't receiving any requests. What URL are you visiting?

**Comment by YannBrrd** [comment]
http://localhost:8081/hub/user/ybarraud/

**Comment by minrk** [comment]
You should be visiting `localhost:8000`. JupyterHub should only be accessed via the proxy, otherwise none of the redirects work.

**Comment by YannBrrd** [comment]
Oh ! My bad ! 

Runs now : -)

Need to uddate requirments to add pyzmq, ,jsonschema, terminado.

I'll try packaging now !

:+1: 

Thanks for support.
