### ISSUE TITLE
Auth problems with `@` in the username

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyterhub#218]
I have students who keep putting their email address into the username. When they do this, there is an odd state that happens - the auth looks like it may be passing (using PAM), and I can see a single user server start, but the user sees a 500 page after auth. I am guessing that the PAM auth is raising a weird exception that we are not handling properly.

**Comment by minrk** [comment]
@ellisonbg the traceback will be in your logs. Can you share it?

**Comment by ksolan** [comment]
Ran into the same issue when using emails as usernames (user@test.com, for example):
```
Traceback (most recent call last):
      File "/home/user/venv3/lib/python3.4/site-packages/tornado/web.py", line 1348, in _execute
        result = yield result
      File "/home/user/custom-auth/customauth.py", line 103, in post
        self.set_login_cookie(user)
      File "/home/user/venv3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 174, in set_login_cookie
        self.set_server_cookie(user)
      File "/home/user/venv3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 160, in set_server_cookie
        path=user.server.base_url,
      File "/home/user/venv3/lib/python3.4/site-packages/tornado/web.py", line 578, in set_secure_cookie
        expires_days=expires_days, **kwargs)
      File "/home/user/venv3/lib/python3.4/site-packages/tornado/web.py", line 513, in set_cookie
        self._new_cookie[name] = value
      File "/usr/lib/python3.4/http/cookies.py", line 489, in __setitem__
        self.__set(key, rval, cval)
      File "/usr/lib/python3.4/http/cookies.py", line 483, in __set
        M.set(key, real_value, coded_value)
      File "/usr/lib/python3.4/http/cookies.py", line 363, in set
        raise CookieError("Illegal key value: %s" % key)
    http.cookies.CookieError: Illegal key value: jupyter-hub-token-user@test.com
```
Apparently the '@' character is illegal in cookie keys.

**Comment by ssanderson** [comment]
seems like the fix for this is probably to base64 the username?

**Comment by ksolan** [comment]
Made the base-64 fix in https://github.com/jupyter/jupyterhub/pull/230, but it breaks compatibility with older singleuser servers, as @minrk noted. 

Another option would be to replace all illegal chars with '-' or "\_", which wouldn't affect existing singleuser servers, but it would introduce the possibility of colliding usernames ("test_user" and "test@user" would have the same cookie), which is bad. Or JupyterHub could just disallow usernames containing illegal cookie chars altogether (legal chars according to http.cookies https://github.com/python/cpython/blob/3.4/Lib/http/cookies.py#L159: `string.ascii_letters + string.digits + "!#$%&'*+-.^_`|~:"`).

**Comment by minrk** [comment]
@ksolan *any* change to the cookie name will require relaunching all single-user servers. It's not a huge deal, but it's significant compared to most updates to the Hub that don't require killing all the user servers..
