### ISSUE TITLE
After install and start of JupyterHub, fails with not finding template pages 

### ISSUE THREAD

**Issue by nenads79** [jupyter/jupyterhub#242]
Deployed according to instructions JupyterHub form master or stable version, even used Anaconda Python 3.4 release, no matter same error after starting jupyterhub and hitting URL it redirects URL:8000/hub/ gives empty page an log on console is:

```
Startup of server #:/ jupyterhub
[I 2015-04-26 11:01:19.196 JupyterHub app:523] Writing cookie_secret to /home/sysops/tmp/jupyterhub_cookie_secret
[W 2015-04-26 11:01:19.257 JupyterHub app:245]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[I 2015-04-26 11:01:19.274 JupyterHub app:602] Not using whitelist. Any authenticated user will be allowed.
[I 2015-04-26 11:01:19.299 JupyterHub app:733] Starting proxy @ http://localhost:8000/
11:01:19.417 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
11:01:19.421 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-04-26 11:02:10.719 JupyterHub web:1825] 302 GET / (127.0.0.1) 2.45ms
[I 2015-04-26 11:02:10.937 JupyterHub web:1825] 302 GET /hub (127.0.0.1) 2.40ms
[E 2015-04-26 11:02:11.056 JupyterHub web:1421] Uncaught exception GET /hub/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/hub/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8000', 'X-Forwarded-Port': '8000', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Proto': 'http', 'X-Forwarded-For': '127.0.0.1', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0', 'Accept-Language': 'en-US,en;q=0.5', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Connection': 'close'})
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.4/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/pages.py", line 28, in get
        login_url=self.settings['login_url'],
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 281, in render_template
        template = self.get_template(name)
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 277, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/environment.py", line 791, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/environment.py", line 765, in _load_template
        template = self.loader.load(self, name, globals)
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/loaders.py", line 178, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: index.html

[E 2015-04-26 11:02:11.070 JupyterHub web:930] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.4/site-packages/tornado/web.py", line 928, in send_error
        self.write_error(status_code, **kwargs)
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 329, in write_error
        html = self.render_template('error.html', **ns)
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 281, in render_template
        template = self.get_template(name)
      File "/opt/anaconda3/lib/python3.4/site-packages/jupyterhub/handlers/base.py", line 277, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/environment.py", line 791, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/environment.py", line 765, in _load_template
        template = self.loader.load(self, name, globals)
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/opt/anaconda3/lib/python3.4/site-packages/jinja2/loaders.py", line 178, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: error.html

[E 2015-04-26 11:02:11.078 JupyterHub web:1825] 500 GET /hub/ (127.0.0.1) 36.58ms
```

What am I missing in this install is there a specific place that I have to start it, or I have to start somethin before jupiterhub command. I have tried Ipython notebook it works. But junyperhub over proxy gives errors I have searched google for similar problems but no luck. 
Please can anyone help?

**Comment by minrk** [comment]
@nenads79 Can you post the output of the installation? It seems like it didn't install correctly.

**Comment by nenads79** [comment]
By trying to get output I fresh installed anaconda and jupyterhub 010 release version but used next set:
pip install --upgrade pip
pip install --upgrade -r requirements.txt
pip install --upgrade .
(this was the first time it took about 2 minutes to complete)
Installing collected packages: jupyterhub
  Running setup.py install for jupyterhub
Successfully installed jupyterhub-0.1.0 -- (this was also the result from the previous installs)
pip install --upgrade "ipython[notebook]"
And magically it works, (it has some problem with kernel lost connection and not connecting but I will work on that) you were right it didn't install correctly (I tried regular procedure 5 times and same result. But now it passed just to be on safe side I will try a clean install to be certain it must have been a problem with some python package)
Thanks
