### ISSUE TITLE
500 : Internal Server Error KeyError: 'user'

### ISSUE THREAD

**Issue by sendit2me** [jupyter/jupyterhub#244]
Hi,

I'm trying to install jupyterhub locally.
but running and connecting to the server I get a 500, I can get to the administrator pages (when sudo jupyterhub 'ing) but not add users etc.

however when I go to the root page (or users dashboard) I get a 500 with :
Uncaught exception GET /user/user/tree (127.0.0.1)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 2613, in wrapper
        if not self.current_user:
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1028, in current_user
        self._current_user = self.get_current_user()
      File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 72, in get_current_user
        return self.login_handler.get_user(self)
      File "/src/jupyterhub/jupyterhub/singleuser.py", line 95, in get_user
        user = auth_data['user']
    KeyError: 'user'

any ideas ?

**Comment by minrk** [comment]
broken by a recent patch. Should be fixed in master.

**Comment by sendit2me** [comment]
Thanks.
That worked
