### ISSUE TITLE
hub can't load notebook kernel from venv

### ISSUE THREAD

**Issue by omerbenamram** [jupyter/jupyterhub#270]
Hi!

I've tried to setup a multi-lang server on my linux machine.

I'm getting the following stacktrace when trying to launch a clingkernel notebook

> [I 2015-07-10 23:36:16.998 JupyterHub log:100] 200 GET     /ipython/hub/api/authorizations/cookie/jupyter-hub-token-omer/[secret] (omer@::1) 9.87ms
[I 2015-07-10 23:36:25.027 omer handlers:172] Creating new notebook in 
[E 2015-07-10 23:36:26.952 omer handlers:405] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/site-packages/IPython/html/base/handlers.py", line 394, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python3.4/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/usr/local/lib/python3.4/site-packages/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "/usr/local/lib/python3.4/site-packages/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
        kernel_name=kernel_name, **kwargs)
      File "/usr/local/lib/python3.4/site-packages/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
        km.start_kernel(**kwargs)
      File "/usr/local/lib/python3.4/site-packages/IPython/kernel/manager.py", line 240, in start_kernel
        **kw)
      File "/usr/local/lib/python3.4/site-packages/IPython/kernel/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/usr/local/lib/python3.4/site-packages/IPython/kernel/launcher.py", line 213, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/local/lib/python3.4/subprocess.py", line 859, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.4/subprocess.py", line 1457, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    **PermissionError: [Errno 13] Permission denied**

[E 2015-07-10 23:36:26.957 omer log:46] {
      "Cookie": "jupyter-hub-token-omer=\"2|1:0|10:1436560576|22:jupyter-hub-token-omer|44:OWJmMzYyZTM2YjQ5NGJjZGFmZjdlNWRiZDc3YjQ4MzA=|c11f5d2979e9b1001b8e0cdb7e78b049bb6ce79f8cebfcce7be07ae4505e1857\"; wanted_view2=details; advanced_toggle_checked=1; manage_view2=details; snatched_view2=list; soon_view2=thumbs; suggestions_charts_menu_selected=suggestions; late_view2=list; filter=all",
      "X-Forwarded-Port": "443,443",
      "Dnt": "1",
      "X-Forwarded-Server": <myserver>,
      "Origin": <myserver>
      "Referer": "<myserver>/ipython/user/omer/notebooks/Untitled8.ipynb?kernel_name=cling",
      "Connection": "close",
      "X-Forwarded-Host": <myserver>,
      "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36",
      "X-Real-Ip": "10.0.0.136",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Content-Type": "application/json",
      "Accept-Language": "en-US,en;q=0.8,he;q=0.6",
      "Host": "benamram.co",
      "X-Forwarded-Proto": "https,https",
      "X-Forwarded-For": "10.0.0.136,::ffff:127.0.0.1",
      "X-Forwarded-Ssl": "on",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "75"
    }
[E 2015-07-10 23:36:26.957 omer log:47] 500 POST /ipython/user/omer/api/sessions (10.0.0.136) 25.61ms referer=<myserver>/ipython/user/omer/notebooks/Untitled8.ipynb?kernel_name=cling

i have no problem running:
>ipython console --kernel cling 

The server running jupyterhub is IPython 3.2 - Python 3.4
the kernel.json for my cling kernel is referring to a virtualenv installation containing IPython 4.0 dev, like so:

>{
  "display_name": "C++",
  "argv": [
      "/root/Envs/cling/bin/python",
      "-m",
      "clingkernel",
      "-f",
      "{connection_file}"
  ]
}

any suggestions?

thanks!

**Comment by minrk** [comment]
Can you start a web terminal from the notebook dashboard, and compare the output of:

```
whoami
echo $PATH
ipython kernelspec list
ipython console --kernel cling
```

with the same in a regular terminal?

**Comment by omerbenamram** [comment]
nice.
whoami in the terminal echoes the logged on user (the server running as root).

path seems to be the same.
kernels are the same

last output seems to echo the same traceback (permission denied):

[omer@penny ~]$ ipython console --kernel cling                                                                                                 
Traceback (most recent call last):                                                                                                             
  File "/usr/local/bin/ipython", line 9, in <module>                                                                                           
    load_entry_point('ipython==3.2.0', 'console_scripts', 'ipython')()                                                                         
  File "/usr/local/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython                                                
    return launch_new_instance(argv=argv, **kwargs)                                                                                            
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 573, in launch_instance                                    
    app.initialize(argv)                                                                                                                       
  File "<string>", line 2, in initialize                                                                                                       
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error                                  
    return method(app, *args, **kwargs)                                                                                                        
  File "/usr/local/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 321, in initialize                                             
    super(TerminalIPythonApp, self).initialize(argv)                                                                                           
  File "<string>", line 2, in initialize                                                                                                       
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error                                  
    return method(app, *args, **kwargs)                                                                                                        
  File "/usr/local/lib/python3.4/site-packages/IPython/core/application.py", line 369, in initialize                                           
    self.parse_command_line(argv)                                                                                                              
  File "/usr/local/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line                                     
    return super(TerminalIPythonApp, self).parse_command_line(argv)                                                                            
  File "<string>", line 2, in parse_command_line                                                                                               
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error                                  
    return method(app, *args, **kwargs)                                                                                                        
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 471, in parse_command_line                                 
    return self.initialize_subcommand(subc, subargv)                                                                                           
  File "<string>", line 2, in initialize_subcommand                                                                                            
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error                                  
    return method(app, *args, **kwargs)                                                                                                        
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 409, in initialize_subcommand                              
    self.subapp.initialize(argv)                                                                                                               
  File "<string>", line 2, in initialize                                                                                                       
  File "/usr/local/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error                                  
    return method(app, *args, **kwargs)                                                                                                        
  File "/usr/local/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 332, in initialize                                             
    self.init_shell()                                                                                                                          
  File "/usr/local/lib/python3.4/site-packages/IPython/terminal/console/app.py", line 107, in init_shell                                       
    IPythonConsoleApp.initialize(self)                                                                                                         
  File "/usr/local/lib/python3.4/site-packages/IPython/consoleapp.py", line 342, in initialize                                                 
    self.init_kernel_manager()                                                                                                                 
  File "/usr/local/lib/python3.4/site-packages/IPython/consoleapp.py", line 298, in init_kernel_manager                                        
    self.kernel_manager.start_kernel(**kwargs)                                                                                                 
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/manager.py", line 240, in start_kernel                                           
    **kw)                                                                                                                                      
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/manager.py", line 189, in _launch_kernel                                         
    return launch_kernel(kernel_cmd, **kw)                                                                                                     
  File "/usr/local/lib/python3.4/site-packages/IPython/kernel/launcher.py", line 213, in launch_kernel                                         
    proc = Popen(cmd, **kwargs)                                                                                                                
  File "/usr/local/lib/python3.4/subprocess.py", line 859, in __init__                                                                         
    restore_signals, start_new_session)                                                                                                        
  File "/usr/local/lib/python3.4/subprocess.py", line 1457, in _execute_child                                                                  
    raise child_exception_type(errno_num, err_msg)                                                                                             
PermissionError: [Errno 13] Permission denied                                                                                                  
                                                                                                                                               
If you suspect this is an IPython bug, please report it at:                                                                                    
    https://github.com/ipython/ipython/issues                                                                                                  
or send an email to the mailing list at ipython-dev@scipy.org                                                                                  
                                                                                                                                               
You can print a more detailed traceback right now with "%tb", or use "%debug"                                                                  
to interactively debug it.                                                                                                                     
                                                                                                                                               
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:                                                                       
    c.Application.verbose_crash=True 

i'm getting the same permission problem for everything under /root apparently when running as user.

I'll try to fix it :)

**Comment by omerbenamram** [comment]
working now!

awesome!! :)
thanks!

**Comment by Yensan** [comment]
> the kernel.json for my cling kernel is referring to a virtualenv installation containing IPython 4.0 dev, like so:
```json
{
"display_name": "C++",
"argv": [
"/root/Envs/cling/bin/python",
"-m",
"clingkernel",
"-f",
"{connection_file}"
]
}
```
@omerbenamram 
What is it? I want deploy JupyterHub with PAM/SystemdSpawner,  and everyone have his own virtual env.
