### ISSUE TITLE
500 : Internal Server Error - jupyterhub with dockerspawner

### ISSUE THREAD

**Issue by mattwg** [jupyter/jupyterhub#291]
I have JupyterHub running at here at eBay.   The whole Jupyter project is awesome - thanks for all your hard work!  

I now want to try and get this working to use our OpenStack cloud - spawning notebooks on a small cluster using Docker Swarm.  As a first step I want to get the DockerSpawner working on the server.  BTW - I am a data scientist not a sysadmin/coder so please bear with me ;-)

I have a problem now that I am trying to using DockerSpawner and in particular SystemUserSpawner.

I followed the instructions here. I can log into the hub and when I start a server I get no errors in the log:

```
root@jupyter01-8523:~# [I 2015-08-24 17:54:15.073 JupyterHub app:518] Loading cookie_secret from /root/jupyterhub_cookie_secret
[W 2015-08-24 17:54:15.109 JupyterHub app:257] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-08-24 17:54:15.117 JupyterHub app:654] Not using whitelist. Any authenticated user will be allowed.
[I 2015-08-24 17:54:15.128 JupyterHub app:1032] Hub API listening on http://localhost:8081/hub/
[I 2015-08-24 17:54:15.132 JupyterHub app:789] Starting proxy @ http://*:8000/
17:54:15.255 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
17:54:15.258 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-08-24 17:54:15.340 JupyterHub app:1055] JupyterHub is now running at http://localhost:8000/
[I 2015-08-24 17:54:18.943 JupyterHub log:100] 200 GET /hub/ (@10.254.185.51) 31.87ms
[I 2015-08-24 17:54:23.109 JupyterHub dockerspawner:333] Found existing container 'jupyter-magardner' (id: a6cba20)
[I 2015-08-24 17:54:23.109 JupyterHub dockerspawner:338] Starting container 'jupyter-magardner' (id: a6cba20)
[I 2015-08-24 17:54:24.434 JupyterHub base:277] User magardner server took 1.378 seconds to start
[I 2015-08-24 17:54:24.434 JupyterHub orm:170] Adding user magardner to proxy /user/magardner => http://127.0.0.1:32770
[I 2015-08-24 17:54:24.462 JupyterHub log:100] 302 POST /hub/login?next= (@10.254.185.51) 1637.46ms
[I 2015-08-24 17:54:24.462 JupyterHub login:76] User logged in: magardner
[I 2015-08-24 17:54:24.501 JupyterHub log:100] 302 GET /hub/ (magardner@10.254.185.51) 11.75ms
```
But in the web browser I get 500 : Internal Server Error.  Any ideas what could be going on?  I can stop the server from the Control Panel just fine.  

For now I am running JupyterHub as sudo - I will tighten that up when I can spawn docker containers.  

Any ideas that might help me here? 

Thanks,
Matt

**Comment by jhamrick** [comment]
Hey Matt,

Can you get any logs from the spawned container (looks like it’s called jupyter-magardner)? It might be the notebook server that’s giving the 500 error, rather than JupyterHub.

Also in case you hadn’t seen it, I have a spawner that builds on SystemUserSpawner but launches containers using swarm: https://github.com/compmodels/jupyterhub/blob/master/swarmspawner.py <https://github.com/compmodels/jupyterhub/blob/master/swarmspawner.py>

Cheers,
Jess

**Comment by mattwg** [comment]
Hi Jess - you and your blog were my inspiration on this and I hope to use your swarm spawner ;-)
I only started using docker a week back - how do I get the logs from the spawned container?
Matt

**Comment by mattwg** [comment]
Found how to get logs (sudo docker logs jupyter-magardner)

There are exceptions in the log:
```
[I 2015-08-25 01:25:43.817 magardner notebookapp:1072] The IPython Notebook is running at: http://0.0.0.0:8888/user/magardner/
[I 2015-08-25 01:25:43.817 magardner notebookapp:1073] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2015-08-25 01:25:43.952 magardner log:47] 302 GET /user/magardner (172.17.42.1) 1.50ms
Creating user magardner (110070535)
useradd: user 'magardner' already exists
[I 2015-08-25 01:56:34.550 magardner notebookapp:639] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 2015-08-25 01:56:34.585 magardner notebookapp:1072] Serving notebooks from local directory: /home/magardner
[I 2015-08-25 01:56:34.585 magardner notebookapp:1072] 0 active kernels 
[I 2015-08-25 01:56:34.585 magardner notebookapp:1072] The IPython Notebook is running at: http://0.0.0.0:8888/user/magardner/
[I 2015-08-25 01:56:34.586 magardner notebookapp:1073] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2015-08-25 01:56:34.987 magardner log:47] 302 GET /user/magardner (172.17.42.1) 1.85ms
[I 2015-08-25 01:56:35.062 magardner log:47] 302 GET /user/magardner/ (10.254.185.51) 1.02ms
[E 2015-08-25 01:56:35.097 magardner web:1496] Uncaught exception GET /user/magardner/tree (10.254.185.51)
    HTTPServerRequest(protocol='http', host='10.65.197.128:8000', method='GET', uri='/user/magardner/tree', version='HTTP/1.1', remote_ip='10.254.185.51', headers={'Accept-Language': 'en-US,en;q=0.5', 'Cookie': 'jupyter-hub-token-magardner="2|1:0|10:1440467795|27:jupyter-hub-token-magardner|44:ZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU=|48af847e4fcff45c8a4b8527a879b9b696bb8f2158768dd2a2727bd5ae225617"', 'Accept-Encoding': 'gzip, deflate', 'Host': '10.65.197.128:8000', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0', 'X-Forwarded-Port': '8000', 'Connection': 'close', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Referer': 'http://10.65.197.128:8000/hub/home', 'X-Forwarded-Proto': 'http', 'X-Forwarded-For': '10.254.185.51'})
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib/python3.4/http/client.py", line 1065, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
        self.endheaders(body)
      File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
        self.send(msg)
      File "/usr/lib/python3.4/http/client.py", line 841, in send
        self.connect()
      File "/usr/lib/python3.4/http/client.py", line 819, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python3.4/socket.py", line 509, in create_connection
        raise err
      File "/usr/lib/python3.4/socket.py", line 500, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 111] Connection refused
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 607, in urlopen
        raise MaxRetryError(self, url, e)
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /hub/api/authorizations/cookie/jupyter-hub-token-magardner/2%7C1%3A0%7C10%3A1440467795%7C27%3Ajupyter-hub-token-magardner%7C44%3AZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU%3D%7C48af847e4fcff45c8a4b8527a879b9b696bb8f2158768dd2a2727bd5ae225617 (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 2704, in wrapper
        if not self.current_user:
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1076, in current_user
        self._current_user = self.get_current_user()
      File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 83, in get_current_user
        return self.login_handler.get_user(self)
      File "/usr/local/bin/jupyterhub-singleuser", line 92, in get_user
        auth_data = JupyterHubLoginHandler.verify_token(self, self.cookie_name, encrypted_cookie)
      File "/usr/local/bin/jupyterhub-singleuser", line 61, in verify_token
        headers = {'Authorization' : 'token %s' % hub_api_key},
      File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 378, in send
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /hub/api/authorizations/cookie/jupyter-hub-token-magardner/2%7C1%3A0%7C10%3A1440467795%7C27%3Ajupyter-hub-token-magardner%7C44%3AZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU%3D%7C48af847e4fcff45c8a4b8527a879b9b696bb8f2158768dd2a2727bd5ae225617 (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
[E 2015-08-25 01:56:35.136 magardner log:46] {
      "Host": "10.65.197.128:8000",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Cookie": "jupyter-hub-token-magardner=\"2|1:0|10:1440467795|27:jupyter-hub-token-magardner|44:ZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU=|48af847e4fcff45c8a4b8527a879b9b696bb8f2158768dd2a2727bd5ae225617\"",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0",
      "Connection": "close",
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Port": "8000",
      "Referer": "http://10.65.197.128:8000/hub/home",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-For": "10.254.185.51"
    }
[E 2015-08-25 01:56:35.136 magardner log:47] 500 GET /user/magardner/tree (10.254.185.51) 48.94ms referer=http://10.65.197.128:8000/hub/home
```

**Comment by jhamrick** [comment]
Ok, that's what I suspected -- it looks like the user server can't talk to JupyterHub because JupyterHub is refusing connections. It looks like you were restarting an existing container, and so one possibility is that the existing container is using an out-of-date token or something. I would recommend trying:

1. Stop JupyterHub
2. Remove and delete your existing notebook server container (`docker stop jupyter-magardner && docker rm jupyter-magardner`)
3. Generate JPY_COOKIE_SECRET and CONFIGPROXY_AUTH_TOKEN (as described [here](https://github.com/jupyter/jupyterhub/blob/master/docs/getting-started.md#security)) ahead of time and set them as environment variables in the shell where you launch JupyterHub
4. Relaunch JupyterHub

Another possibility is that it looks like you're trying to connect to the hub api via localhost, but "localhost" inside the docker container isn't the same as it is on the rest of the machine. I would try configuring the `DockerSpawner.hub_ip_connect` variable in your jupyterhub_config to point to the actual IP where the hub is running rather than localhost.

**Comment by mattwg** [comment]
Hi Jess - I have followed your advice.  I created a self signed certificate for now - following the guidance [here](https://help.ubuntu.com/12.04/serverguide/certificates-and-security.html).  

I stopped the hub and removed the notebook server container.  I then followed all the steps in the document you referred me to [here](https://github.com/jupyter/jupyterhub/blob/master/docs/getting-started.md#security) - now my jupyterhub_config.py looks like this

```
c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.JupyterHub.port = 443
c.JupyterHub.ssl_key = '/root/server.key'
c.JupyterHub.ssl_cert = '/root/server.crt'
c.JupyterHub.cookie_secret_file = '/root/jupyterhub_cookie_secret'
c.DockerSpawner.hub_ip_connect = '10.65.197.128'
```

When I restart the hub the output in the hub logfile looks like this:

```
root@jupyter01-8523:~# jupyterhub &
[1] 14683
root@jupyter01-8523:~# [I 2015-08-24 20:45:48.660 JupyterHub app:510] Loading cookie_secret from env[JPY_COOKIE_SECRET]
[I 2015-08-24 20:45:48.711 JupyterHub app:654] Not using whitelist. Any authenticated user will be allowed.
[I 2015-08-24 20:45:48.733 JupyterHub dockerspawner:276] Container 'jupyter-magardner' is gone
[W 2015-08-24 20:45:48.733 JupyterHub dockerspawner:247] container not found
[I 2015-08-24 20:45:48.747 JupyterHub app:1032] Hub API listening on http://localhost:8081/hub/
[I 2015-08-24 20:45:48.751 JupyterHub app:789] Starting proxy @ http://*:443/
20:45:48.889 - info: [ConfigProxy] Proxying https://*:443 to http://localhost:8081
20:45:48.892 - info: [ConfigProxy] Proxy API at http://localhost:444/api/routes
[I 2015-08-24 20:45:48.959 JupyterHub app:1055] JupyterHub is now running at http://localhost:443/
[I 2015-08-24 20:46:20.763 JupyterHub log:100] 302 GET / (@10.254.185.51) 4.19ms
[I 2015-08-24 20:46:20.788 JupyterHub log:100] 302 GET /hub (@10.254.185.51) 0.86ms
[I 2015-08-24 20:46:20.832 JupyterHub log:100] 302 GET /hub/ (magardner@10.254.185.51) 6.52ms
[I 2015-08-24 20:46:20.888 JupyterHub log:100] 200 GET /hub/home (magardner@10.254.185.51) 34.86ms
[I 2015-08-24 20:46:23.227 JupyterHub dockerspawner:276] Container 'jupyter-magardner' is gone
[W 2015-08-24 20:46:23.228 JupyterHub dockerspawner:247] container not found
[I 2015-08-24 20:46:23.266 JupyterHub dockerspawner:276] Container 'jupyter-magardner' is gone
[I 2015-08-24 20:46:23.349 JupyterHub dockerspawner:328] Created container 'jupyter-magardner' (id: 7ebbc41) from image jupyter/systemuser
[I 2015-08-24 20:46:23.350 JupyterHub dockerspawner:338] Starting container 'jupyter-magardner' (id: 7ebbc41)
[I 2015-08-24 20:46:24.625 JupyterHub base:277] User magardner server took 1.397 seconds to start
[I 2015-08-24 20:46:24.626 JupyterHub orm:170] Adding user magardner to proxy /user/magardner => http://127.0.0.1:32786
[I 2015-08-24 20:46:24.659 JupyterHub log:100] 302 GET /hub/user/magardner/ (magardner@10.254.185.51) 1438.88ms
```

I now have to browse to the https url on port 443 to load the hub in the browser.  Unfortunately when I start the notebook I still get the 500 error though.

The container log has this exception:

```
[I 2015-08-25 03:46:24.681 magardner log:47] 302 GET /user/magardner/ (10.254.185.51) 0.99ms
[E 2015-08-25 03:46:24.714 magardner web:1496] Uncaught exception GET /user/magardner/tree (10.254.185.51)
    HTTPServerRequest(protocol='https', host='10.65.197.128', method='GET', uri='/user/magardner/tree', version='HTTP/1.1', remote_ip='10.254.185.51', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'X-Forwarded-For': '10.254.185.51', 'X-Forwarded-Proto': 'https', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'close', 'Host': '10.65.197.128', 'X-Forwarded-Port': '443', 'Referer': 'https://10.65.197.128/hub/home', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0', 'Cookie': 'jupyter-hub-token-magardner="2|1:0|10:1440474384|27:jupyter-hub-token-magardner|44:ZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU=|a44c8300ba8b7d1a4ef068a823b8350510a14cb25f70e4969c7b2a463cdafc05"'})
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib/python3.4/http/client.py", line 1065, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
        self.endheaders(body)
      File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
        self.send(msg)
      File "/usr/lib/python3.4/http/client.py", line 841, in send
        self.connect()
      File "/usr/lib/python3.4/http/client.py", line 819, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python3.4/socket.py", line 509, in create_connection
        raise err
      File "/usr/lib/python3.4/socket.py", line 500, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 111] Connection refused
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 607, in urlopen
        raise MaxRetryError(self, url, e)
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.65.197.128', port=8081): Max retries exceeded with url: /hub/api/authorizations/cookie/jupyter-hub-token-magardner/2%7C1%3A0%7C10%3A1440474384%7C27%3Ajupyter-hub-token-magardner%7C44%3AZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU%3D%7Ca44c8300ba8b7d1a4ef068a823b8350510a14cb25f70e4969c7b2a463cdafc05 (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 2704, in wrapper
        if not self.current_user:
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1076, in current_user
        self._current_user = self.get_current_user()
      File "/usr/local/lib/python3.4/dist-packages/IPython/html/base/handlers.py", line 83, in get_current_user
        return self.login_handler.get_user(self)
      File "/usr/local/bin/jupyterhub-singleuser", line 92, in get_user
        auth_data = JupyterHubLoginHandler.verify_token(self, self.cookie_name, encrypted_cookie)
      File "/usr/local/bin/jupyterhub-singleuser", line 61, in verify_token
        headers = {'Authorization' : 'token %s' % hub_api_key},
      File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 378, in send
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.65.197.128', port=8081): Max retries exceeded with url: /hub/api/authorizations/cookie/jupyter-hub-token-magardner/2%7C1%3A0%7C10%3A1440474384%7C27%3Ajupyter-hub-token-magardner%7C44%3AZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU%3D%7Ca44c8300ba8b7d1a4ef068a823b8350510a14cb25f70e4969c7b2a463cdafc05 (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
[E 2015-08-25 03:46:24.751 magardner log:46] {
      "Accept-Language": "en-US,en;q=0.5",
      "Connection": "close",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "https://10.65.197.128/hub/home",
      "X-Forwarded-For": "10.254.185.51",
      "X-Forwarded-Port": "443",
      "X-Forwarded-Proto": "https",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0",
      "Cookie": "jupyter-hub-token-magardner=\"2|1:0|10:1440474384|27:jupyter-hub-token-magardner|44:ZTQzZTkxMzE5NjMzNDFkNGI2MGZiNTkzYTAzMDA0NTU=|a44c8300ba8b7d1a4ef068a823b8350510a14cb25f70e4969c7b2a463cdafc05\"",
      "Host": "10.65.197.128"
    }
[E 2015-08-25 03:46:24.751 magardner log:47] 500 GET /user/magardner/tree (10.254.185.51) 44.66ms referer=https://10.65.197.128/hub/home
```

Any other ideas?

**Comment by jhamrick** [comment]
Hmm, in the error logs it looks like it's trying to connect to 10.65.197.128:8081. Where does that IP address come from? It's not the same as the hub ip you specified, which is 10.254.185.51. Do you have an additional proxy somewhere in there or something? Where does that ip address come from?

**Comment by mattwg** [comment]
Good question!  Let me check.

**Comment by mattwg** [comment]
10.65.197.128 is the hub ip.
10.254.185.51 is the address of my laptop where I was connecting to the hub from.

I wonder if port 8081 is not open in the hub?

**Comment by jhamrick** [comment]
Ahh, sorry, you're right, I misread what you had posted in your config.

Can you try setting `c.JupyterHub.hub_ip = '10.65.197.128'` as well?

**Comment by mattwg** [comment]
That worked!  Thanks for help Jess.  

For others looking to do this in future (or me next week!) here was my final jupyter_config.py:

```
c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.JupyterHub.port = 443
c.JupyterHub.ssl_key = '/root/server.key'
c.JupyterHub.ssl_cert = '/root/server.crt'
c.JupyterHub.cookie_secret_file = '/root/jupyterhub_cookie_secret'
c.DockerSpawner.hub_ip_connect = '10.65.197.128'
c.JupyterHub.hub_ip = '10.65.197.128'
```
Next I want to get swarm running!

**Comment by rgbkrk** [comment]
Thanks for rocking through it and posting your final config!

**Comment by jerrylam** [comment]
It will definitely help if the documentation can be updated according to the configurations here. As of now, one cannot use the dockerspawner following the user guide.

**Comment by Lab41PaulM** [comment]
This fix worked for me as well! Thanks.

**Comment by ian-contiamo** [comment]
This solved my problem too. For the record, I had to take these two steps:

1. remove existing docker processes with `docker rm` (probably because, as suggested, they were using out-of-date tokens);
2. set the hub IP to my laptop's IP and tell the spawner what the hub IP is, because localhost is not properly resolved inside the docker image.

 ```
c.DockerSpawner.hub_ip_connect = '192.168.x.x'
c.JupyterHub.hub_ip = '192.168.x.x'
```
I will try to suggest a change in the Readme, because as @jerrylam said, the dockerspawner does not run out of the box. Thanks for your help @jhamrick!

**Comment by edsu** [comment]
@ian-contiamo thank you so much for the extra detail about removing any existing docker containers!

**Comment by akshar-raaj** [comment]
Worked for me too! Thanks @mattwg and @jhamrick

**Comment by digglife** [comment]
Removing the existing container works for me. Thanks!

**Comment by jeffwji** [comment]
Bad idea to fix the IP in configuration file, as the IP was assigned dynamic from docker, you will have no idea what it will be.
