### ISSUE TITLE
pip3 install fails during bower install

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyterhub#32]
`pip3`'s logging borks on bower logging output `└── jquery#2.0.3`, making installation not exit cleanly.

```
...
    bower requirejs#~2.1           install requirejs#2.1.15
    bower jquery#~2.0              install jquery#2.0.3
    bower moment#~2.7              install moment#2.7.0

    font-awesome#4.1.0 share/jupyter/static/components/font-awesome

    bootstrap#3.1.1 share/jupyter/static/components/bootstrap
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 681, in call_subprocess
    logger.log(level, line)
  File "/usr/lib/python3/dist-packages/pip/log.py", line 170, in log
    raise(e)
  File "/usr/lib/python3/dist-packages/pip/log.py", line 163, in log
    consumer.write(write_content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-6: ordinal not in range(128)

Storing debug log for failure in /.pip/pip.log
```

**Comment by merqurio** [comment]
+1 we have the same problem

**Comment by gzepr** [comment]
same here on debian

**Comment by Gnimuc** [comment]
same error on ubuntu14.04 within a docker container.

following the instruction, I run `pip3 install .` but got some errors below:
```
less-plugin-clean-css@1.5.0 node_modules/less-plugin-clean-css
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 699, in call_subprocess
    logger.log(level, line)
  File "/usr/lib/python3/dist-packages/pip/log.py", line 162, in log
    consumer.write(write_content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-6: ordinal not in range(128)

Storing debug log for failure in /root/.pip/pip.log
```
I thought it was the **`lessc` being unavailable** case, so I run `npm install`, in the end, I got these errors:
```
 bower moment#~2.7              install moment#2.7.0
    
    jquery#2.0.3 share/jupyter/hub/static/components/jquery
    
    font-awesome#4.1.0 share/jupyter/hub/static/components/font-awesome
    
    bootstrap#3.1.1 share/jupyter/hub/static/components/bootstrap
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 699, in call_subprocess
    logger.log(level, line)
  File "/usr/lib/python3/dist-packages/pip/log.py", line 162, in log
    consumer.write(write_content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-6: ordinal not in range(128)

Storing debug log for failure in /root/.pip/pip.log
```
my `pip3` version is `pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)` but `bower` seems not to be installed correctly:
```
root@bdec8be3f4e7:~/jupyterhub# bower --version
bash: bower: command not found
```
I tried to install `bower` manually using `npm install -g bower`, but didn't fix the error.

I noticed that  both rgbkrk and I were running within docker container,  is this probably a reason?

**Comment by minrk** [comment]
@Gnimuc try updating your pip (current is 7.1). You do not need a global install of bower or lessc, just npm.

**Comment by Gnimuc** [comment]
@minrk got fixed after I've updated my pip. many thanks :+1:  & sorry for disturbing.

**Comment by minrk** [comment]
@Gnimuc no problem, chalking it up to a pip bug.
