### ISSUE TITLE
Proxy target missing, then 500 error, then "your server is starting up", for ONE user only (with sudospawner)

### ISSUE THREAD

**Issue by nbonnotte** [jupyter/jupyterhub#333]
I'm using a JupyterHub running without being root, with sudospawner.

Everything works fine, except for ONE of my users, who cannot get a notebook started. Sometimes he gets a simple "Proxy target missing" error message, sometimes a 500 error, but most of the times it "your server is starting up" (but nothing ever happens).

Here are the logs I get from the `jupyterhub` command when he goes to the landing page:

```
[I 151109 09:53:30 mediator:62] Spawning /opt/jupyterhub/env3/bin/python3 -m jupyterhub.singleuser --user=remi --port=38268 --cookie-name=jupyter-hub-token-remi --base-url=/user/remi --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost --debug
[D 2015-11-09 09:53:30.975 JupyterHub spawner:219] Polling subprocess every 30s
[W 2015-11-09 09:53:40.809 JupyterHub base:290] User remi server is slow to start
[I 2015-11-09 09:53:40.818 JupyterHub log:100] 302 GET /hub/user/remi/tree/notebook (remi@192.168.103.103) 10542.25ms
[I 2015-11-09 09:53:40.832 JupyterHub log:100] 302 GET /user/remi/tree/notebook (@192.168.103.103) 1.10ms
[I 2015-11-09 09:53:40.849 JupyterHub log:100] 200 GET /hub/user/remi/tree/notebook (remi@192.168.103.103) 5.51ms
[D 2015-11-09 09:53:40.898 JupyterHub log:100] 304 GET /hub/static/css/style.min.css?v=91ce438c2b069a81fab89be10cab12ce (@192.168.103.103) 1.05ms
[D 2015-11-09 09:53:40.900 JupyterHub log:100] 304 GET /hub/static/components/requirejs/require.js?v=2de44fdcc1fe5e939aa4ce80626b241d (@192.168.103.103) 0.85ms
[D 2015-11-09 09:53:40.902 JupyterHub log:100] 304 GET /hub/static/images/jupyter.png?v=7c4597ba713d804995e8f8dad448a397 (@192.168.103.103) 0.85ms
[D 2015-11-09 09:53:40.937 JupyterHub log:100] 304 GET /hub/static/components/font-awesome/fonts/fontawesome-webfont.woff?v=4.1.0 (@192.168.103.103) 0.91ms
[D 2015-11-09 09:53:40.954 JupyterHub log:100] 304 GET /hub/static/components/jquery/jquery.min.js?v=(%2720151109095222%27,) (@192.168.103.103) 0.97ms
[D 2015-11-09 09:53:45.998 JupyterHub log:100] 304 GET /hub/user/remi/tree/notebook (remi@192.168.103.103) 6.74ms
[D 2015-11-09 09:53:46.021 JupyterHub log:100] 304 GET /hub/static/css/style.min.css?v=91ce438c2b069a81fab89be10cab12ce (@192.168.103.103) 0.54ms
[D 2015-11-09 09:53:46.022 JupyterHub log:100] 304 GET /hub/static/components/requirejs/require.js?v=2de44fdcc1fe5e939aa4ce80626b241d (@192.168.103.103) 0.86ms
[D 2015-11-09 09:53:46.024 JupyterHub log:100] 304 GET /hub/static/images/jupyter.png?v=7c4597ba713d804995e8f8dad448a397 (@192.168.103.103) 0.80ms
[D 2015-11-09 09:53:46.053 JupyterHub log:100] 304 GET /hub/static/components/font-awesome/fonts/fontawesome-webfont.woff?v=4.1.0 (@192.168.103.103) 0.95ms
[D 2015-11-09 09:53:51.161 JupyterHub log:100] 304 GET /hub/user/remi/tree/notebook (remi@192.168.103.103) 6.88ms
[D 2015-11-09 09:53:51.187 JupyterHub log:100] 304 GET /hub/static/css/style.min.css?v=91ce438c2b069a81fab89be10cab12ce (@192.168.103.103) 0.52ms
[D 2015-11-09 09:53:51.188 JupyterHub log:100] 304 GET /hub/static/components/requirejs/require.js?v=2de44fdcc1fe5e939aa4ce80626b241d (@192.168.103.103) 0.44ms
[D 2015-11-09 09:53:51.190 JupyterHub log:100] 304 GET /hub/static/images/jupyter.png?v=7c4597ba713d804995e8f8dad448a397 (@192.168.103.103) 0.48ms
[D 2015-11-09 09:53:51.215 JupyterHub log:100] 304 GET /hub/static/components/font-awesome/fonts/fontawesome-webfont.woff?v=4.1.0 (@192.168.103.103) 0.92ms
[D 2015-11-09 09:53:51.234 JupyterHub log:100] 304 GET /hub/static/components/jquery/jquery.min.js?v=(%2720151109095222%27,) (@192.168.103.103) 0.98ms
[D 2015-11-09 09:53:56.271 JupyterHub log:100] 304 GET /hub/user/remi/tree/notebook (remi@192.168.103.103) 6.09ms
[D 2015-11-09 09:53:56.300 JupyterHub log:100] 304 GET /hub/static/css/style.min.css?v=91ce438c2b069a81fab89be10cab12ce (@192.168.103.103) 0.63ms
[D 2015-11-09 09:53:56.301 JupyterHub log:100] 304 GET /hub/static/components/requirejs/require.js?v=2de44fdcc1fe5e939aa4ce80626b241d (@192.168.103.103) 0.53ms
[D 2015-11-09 09:53:56.303 JupyterHub log:100] 304 GET /hub/static/images/jupyter.png?v=7c4597ba713d804995e8f8dad448a397 (@192.168.103.103) 0.81ms
[D 2015-11-09 09:53:56.332 JupyterHub log:100] 304 GET /hub/static/components/font-awesome/fonts/fontawesome-webfont.woff?v=4.1.0 (@192.168.103.103) 0.91ms
[D 2015-11-09 09:53:56.346 JupyterHub log:100] 304 GET /hub/static/components/jquery/jquery.min.js?v=(%2720151109095222%27,) (@192.168.103.103) 0.96ms
[W 2015-11-09 09:54:01.165 JupyterHub orm:408] remi's server never showed up at http://localhost:38268/user/remi after 30 seconds. Giving up
[E 2015-11-09 09:54:01.410 JupyterHub gen:733] Exception in Future <tornado.concurrent.Future object at 0x7faf8d1c5518> after timeout
    Traceback (most recent call last):
      File "/opt/jupyterhub/env3/lib/python3.4/site-packages/tornado/gen.py", line 729, in error_callback
        future.result()
      File "/opt/jupyterhub/env3/lib/python3.4/site-packages/jupyterhub/orm.py", line 424, in spawn
        raise e
      File "/opt/jupyterhub/env3/lib/python3.4/site-packages/jupyterhub/orm.py", line 400, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/jupyterhub/env3/lib/python3.4/site-packages/jupyterhub/orm.py", line 111, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/opt/jupyterhub/env3/lib/python3.4/site-packages/jupyterhub/utils.py", line 82, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:38268/user/remi didn't respond in 30 seconds
```

My settings:
```
(env3)root@server:# pip freeze
Jinja2==2.8
MarkupSafe==0.23
Pygments==2.0.2
SQLAlchemy==1.0.9
decorator==4.0.4
docker-py==1.2.2
dockerspawner==0.0.1-dev
ipython==3.1.0
ipython-genutils==0.1.0
jsonschema==2.4.0
jupyterhub==0.3.0
mistune==0.7
pamela==0.2.1
pyzmq==14.6.0
requests==2.8.1
simplepam==0.1.5
six==1.9.0
-e git+git@github.com:jupyter/sudospawner.git@7f72bc51deca3ec4e648c4b5b43000f71a9fd00b#egg=sudospawner-origin/HEAD
tornado==4.2.1
traitlets==4.0.0
```

I've basically no idea of what's going on. What could I do to have better logs?

**Comment by nbonnotte** [comment]
Update: now everyone is concerned :'(

**Comment by minrk** [comment]
sudospawner is quite tricky to debug due to some lost output that I haven't been able to figure out. Can you, as one of the users, run the command:

    /opt/jupyterhub/env3/bin/python3 -m jupyterhub.singleuser --user=remi --port=38268 --cookie-name=jupyter-hub-token-remi --base-url=/user/remi --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost --debug

**Comment by nbonnotte** [comment]
I used the solution in #308 and `pip install notebook` solved my problem.

Before, I had done what you suggested, and I got:
```
nicolas@server:~$ sudo -u remi /opt/jupyterhub/env3/bin/python3 -m jupyterhub.singleuser --user=remi --port=38268 --cookie-name=jupyter-hub-token-remi --base-url=/user/remi --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost --debug
/opt/jupyterhub/env3/lib/python3.4/site-packages/IPython/utils/path.py:303: UserWarning: IPython dir '/mnt/qs1/home/nicolas/.ipython' is not a writable location, using a temp directory.
  " using a temp directory.".format(ipdir))
[D 2015-11-09 10:11:02.769 remi application:242] Config changed:
[D 2015-11-09 10:11:02.769 remi application:243] {'SingleUserNotebookApp': {'cookie_name': 'jupyter-hub-token-remi', 'user': 'remi', 'hub_prefix': '/hub/', 'log_level': 10, 'port': 38268, 'ip': 'localhost', 'hub_api_url': 'http://localhost:8081/hub/api', 'base_url': '/user/remi'}}
[D 2015-11-09 10:11:02.780 remi application:224] IPYTHONDIR set to: /tmp/tmpz_vufump
[I 2015-11-09 10:11:02.782 remi application:292] Created profile dir: '/tmp/tmpz_vufump/profile_default'
[D 2015-11-09 10:11:02.782 remi application:233] Searching path ['/mnt/qs1/home/nicolas', '/tmp/tmpz_vufump/profile_default', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[D 2015-11-09 10:11:02.783 remi application:236] Attempting to load config file: ipython_config.py
[D 2015-11-09 10:11:02.783 remi application:252] Attempting to load config file: ipython_notebook_config.py
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/jupyterhub/env3/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 237, in <module>
    main()
  File "/opt/jupyterhub/env3/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 233, in main
    return SingleUserNotebookApp.launch_instance()
  File "/opt/jupyterhub/env3/lib/python3.4/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/opt/jupyterhub/env3/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/jupyterhub/env3/lib/python3.4/site-packages/IPython/html/notebookapp.py", line 1009, in initialize
    self.init_webapp()
  File "/opt/jupyterhub/env3/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 203, in init_webapp
    s['hub_api_key'] = env.pop('JPY_API_TOKEN')
  File "/opt/jupyterhub/env3/lib/python3.4/_collections_abc.py", line 546, in pop
    value = self[key]
  File "/opt/jupyterhub/env3/lib/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'JPY_API_TOKEN'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by minrk** [comment]
ok, glad it's worked out, then.
