### ISSUE TITLE
Can't start single-user server

### ISSUE THREAD

**Issue by zer0n** [jupyter/jupyterhub#335]
After logging in, JupyterHub keeps showing this error.
![image](https://cloud.githubusercontent.com/assets/12666582/11081895/8c45a210-87d5-11e5-871e-fb5bbaee5412.png)

The backend shows this
```
[I 2015-11-11 02:05:55.167 JupyterHub spawner:363] Spawning jupyterhub-singleuser --user=zer0ne --port=40392 --cookie-name=jupyter-hub-token-zer0ne --base-url=/user/zer0ne --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/zer0ne/src/jupyterhub/scripts/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/home/zer0ne/src/jupyterhub/jupyterhub/singleuser.py", line 21, in <module>
    from IPython.utils.traitlets import (
ImportError: No module named 'IPython'
[W 2015-11-11 02:06:05.253 JupyterHub base:290] User zer0ne server is slow to start
[I 2015-11-11 02:06:05.263 JupyterHub log:100] 302 GET /hub/user/zer0ne/ (zer0ne@131.107.192.117) 10675.38ms
[I 2015-11-11 02:06:05.311 JupyterHub log:100] 302 GET /user/zer0ne/ (@131.107.192.117) 0.82ms
[I 2015-11-11 02:06:05.364 JupyterHub log:100] 200 GET /hub/user/zer0ne/ (zer0ne@131.107.192.117) 4.72ms
[I 2015-11-11 02:06:11.927 JupyterHub log:100] 200 GET /hub/user/zer0ne/ (zer0ne@131.107.192.117) 9.21ms
[I 2015-11-11 02:06:18.924 JupyterHub log:100] 200 GET /hub/user/zer0ne/ (zer0ne@131.107.192.117) 8.96ms
[W 2015-11-11 02:06:25.317 JupyterHub orm:408] zer0ne's server never showed up at http://localhost:40392/user/zer0ne after 30 seconds. Giving up
[E 2015-11-11 02:06:25.566 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f551a4306d8> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/home/zer0ne/src/jupyterhub/jupyterhub/orm.py", line 424, in spawn
        raise e
      File "/home/zer0ne/src/jupyterhub/jupyterhub/orm.py", line 400, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/home/zer0ne/src/jupyterhub/jupyterhub/orm.py", line 111, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/home/zer0ne/src/jupyterhub/jupyterhub/utils.py", line 82, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://localhost:40392/user/zer0ne didn't respond in 30 seconds

Last login: Wed Nov 11 02:05:54 UTC 2015
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-31-generic x86_64)
```

Why does it complain that `no module named IPython`?

I'm using the latest source of JupyterHub.

**Comment by minrk** [comment]
What version of JupyterHub? It looks like there are missing dependencies. Try:

    pip3 install --upgrade jupyterhub notebook

**Comment by zer0n** [comment]
Sorry it takes so long to get back. I'm using the latest JupyteHub from GitHub.

After `pip3 install --upgrade jupyterhub notebook`
```
[I 2015-11-13 00:18:28.949 JupyterHub app:517] Loading cookie_secret from /home/zer0ne/env/jupyterhub_cookie_secret
[W 2015-11-13 00:18:28.983 JupyterHub app:257]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2015-11-13 00:18:28.988 JupyterHub app:630] No admin users, admin interface will be unavailable.
[W 2015-11-13 00:18:28.988 JupyterHub app:631] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2015-11-13 00:18:28.988 JupyterHub app:651] Not using whitelist. Any authenticated user will be allowed.
[I 2015-11-13 00:18:29.001 JupyterHub app:1030] Hub API listening on http://localhost:8081/hub/
[I 2015-11-13 00:18:29.010 JupyterHub app:787] Starting proxy @ http://*:8000/
00:18:29.140 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
00:18:29.143 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-11-13 00:18:29.218 JupyterHub app:1053] JupyterHub is now running at http://localhost:8000/
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-31-generic x86_64)

12 packages can be updated.
8 updates are security updates.

sh: 1: cannot create /run/motd.dynamic.new: Permission denied
[I 2015-11-13 00:18:33.913 JupyterHub spawner:363] Spawning jupyterhub-singleuser --user=zer0ne --port=51221 --cookie-name=jupyter-hub-token-zer0ne --base-url=/user/zer0ne --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
Failed to set groups [Errno 1] Operation not permitted
/home/zer0ne/env/python3/lib/python3.4/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Traceback (most recent call last):
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/traitlets/traitlets.py", line 432, in __get__
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zer0ne/env/python3/bin/jupyterhub-singleuser", line 4, in <module>
    main()
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/jupyterhub/singleuser.py", line 233, in main
    return SingleUserNotebookApp.launch_instance()
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/notebook/notebookapp.py", line 1005, in initialize
    self.init_configurables()
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/notebook/notebookapp.py", line 804, in init_configurables
    connection_dir=self.runtime_dir,
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/traitlets/traitlets.py", line 439, in __get__
    value = self._validate(obj, dynamic_default())
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/home/zer0ne/env/python3/lib/python3.4/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/zer0ne/env/python3/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/zer0ne/env/python3/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/zer0ne/.local/share/jupyter'
```

It looks like Jupyter/JupyterHub tried to create `.local/share/jupyter` but failed for some reason.

**Comment by zer0n** [comment]
This is not a JupyterHub problem. So closing this issue.
