### ISSUE TITLE
Bower version 1.7.3 jump breaks development install

### ISSUE THREAD

**Issue by ianabc** [jupyter/jupyterhub#388]
bower has moved to version 1.7.3, this breaks the development install described in the README.md. Running npm install doesn't collect some of the modules that bower needs.

**After some experimentation, this might be restricted to npm & nodejs from EPEL in Centos 7**
```
$ python setup.py js

running js

module.js:340
    throw err;
          ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/jupyterhub/node_modules/bower/node_modules/bower-config/lib/util/rc.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Traceback (most recent call last):
  File "setup.py", line 297, in <module>
    main()
  File "setup.py", line 294, in main
    setup(**setup_args)
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 179, in run
    env=env,
  File "/usr/lib64/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bower', 'install', '--allow-root', '--config.interactive=false']' returned non-zero exit status 8
```

Pinning bower to 1.7.2 in packages.json works for the moment, and I have asked about the issue in the bower live support. e.g. 659602e7dbf1a7203a09326be1f14ed820bfa385

Here is my version information
```
python3.4 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '8ff8693',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/lib/python3.4/site-packages/IPython',
 'ipython_version': '4.0.3',
 'os_name': 'posix',
 'platform': 'Linux-3.10.0-327.4.4.el7.x86_64-x86_64-with-centos-7.2.1511-Core',
 'sys_executable': '/usr/bin/python3.4',
 'sys_platform': 'linux',
 'sys_version': '3.4.3 (default, Jun 19 2015, 05:46:30) \n'
                '[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]'}
```

**Comment by ianabc** [comment]
I've traced this back to an issue with the older version of npm which ships with EPEL for CentOS 7. I'm closing this and will take the bug to the EPEL package maintainer for npm.

**Comment by ianabc** [comment]
The bower maintainers have withdrawn 1.7.3 for the moment until this is sorted out.
