### ISSUE TITLE
Setup allowing any Github user access

### ISSUE THREAD

**Issue by Seanmcn** [jupyter/jupyterhub#466]
Hi there,

Trying to use Jupyterhub for a talk I'm giving on Thursday. I've basically setup a server and want anyone who is in the room to be able to login to the server using their github credentials. Is this possible? It seems possible to automatically add system users but not github users. Having no whitelist allows any Github user to login but once they hit "*Start my Server*" they will get a 500 and I'll see the error `KeyError: 'getpwnam(): name not found: GITHUB_USERNAME'`

Here is my current config:

```
# Github Settings
c.GitHubOAuthenticator.client_id = os.environ['GITHUB_CLIENT_ID']
c.GitHubOAuthenticator.client_secret = os.environ['GITHUB_CLIENT_SECRET']
c.GitHubOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']

# Authentication Setup
c.JupyterHub.authenticator_class = 'oauthenticator.LocalGitHubOAuthenticator'
c.LocalGitHubOAuthenticator.create_system_users = True

# Create empty whitelist and setup admin users
c.Authenticator.whitelist = whitelist = set()
c.Authenticator.admin_users = admin = set()
c.JupyterHub.admin_access = True
    
# Use userlist to determine administrators
with open(join(here, 'userlist')) as f:
    for line in f:
        if not line:
            continue
        parts = line.split()
        name = parts[0]
        if len(parts) > 1 and parts[1] == 'admin':
            admin.add(name)
```

I'd appreciate any feedback of how to approach achieving what I want.

**Comment by minrk** [comment]
This is a bug in JupyterHub that `add_user` isn't called when users login and there is no whitelist. It should be fixed by #467.

If you really want 'any' GitHub user to have access, I might recommend using the DockerSpawner, so that each user is put into a container. That removes the need for creating system users, and avoids this bug:

```python
c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
```

**Comment by Seanmcn** [comment]
@minrk thanks very much, using DockerSpawner has solved my issue! :smile:

**Comment by hayjoss** [comment]
Sorry to resurrect this, but it's happening to me as well out of the box it using Ubuntu 16.04:

```    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 535, in get
        yield self.spawn_single_user(current_user)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/sudospawner/spawner.py", line 90, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/spawner.py", line 770, in get_env
        env = self.user_env(env)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/spawner.py", line 757, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: myGithubAccount'```

Here is my config:

```c.JupyterHub.authenticator_class = 'oauthenticator.GitHubOAuthenticator'
#c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'

c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'

c.GitHubOAuthenticator.oauth_callback_url = 'https://mydomain.co/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = '<clientid>'
c.GitHubOAuthenticator.client_secret = '<clientsecret>'

c.LocalAuthenticator.create_system_users = True

c.GitHubOAuthenticator.whitelist = {'gitHubUser1', 'gitHubUser2', 'gitHubUser3'}
c.GitHubOAuthenticator.admin_users = {'gitHubUser1', 'gitHubUser2', 'gitHubUser3'}
c.Spawner.notebook_dir = 'notebooks/'
c.JupyterHub.ssl_cert = 'secrets/cert.pem'
c.JupyterHub.ssl_key = 'secrets/privkey.pem'```

I installed Jupyterhub a bit differently, I used sudo -H and installed all the pip packages that way, so it's installed on the system. I use my own user account (or sudo) to start `jupyterhub` in my homedir, and for whatever reason this config worked for my own github account (which is not the same as my system username), but is giving the 500 error to each new user.

**Comment by minrk** [comment]
@hayjoss the fix above is in master, but hasn't been released. Can you show the log statements from when the user is created and `pip list`?

**Comment by hayjoss** [comment]
Here is the full error:

```
[E 2017-05-02 17:39:52.076 JupyterHub log:100] 500 GET /hub/user/myGithubAccount (myGithubAccount@::ffff:<my addr>) 61.43ms
[E 2017-05-02 17:39:54.868 JupyterHub user:251] Unhandled error starting myGithubAccount's server: 'getpwnam(): name not found: myGithubAccount'
[E 2017-05-02 17:39:54.881 JupyterHub web:1590] Uncaught exception GET /hub/user/myGithubAccount (::ffff:<my addr>)
    HTTPServerRequest(protocol='https', host='<my domain>', method='GET', uri='/hub/user/myGithubAccount', version='HTTP/1.1', remote_ip='::ffff:<my addr>', headers={'Accept-Encoding': 'gzip, deflate, sdch, br', 'X-Forwarded-Port': '1080', 'X-Forwarded-Proto': 'https', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36', 'Connection': 'close', 'Accept-Language': 'en-US,en;q=0.8', 'Host': '<my domain>', 'Upgrade-Insecure-Requests': '1', 'Cache-Control': 'max-age=0', 'X-Forwarded-For': '::ffff:<my addr>', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Referer': 'https://<my domain>/hub/home', 'Cookie': 'jupyter-hub-token="<my token>"', 'X-Forwarded-Host': '<my domain>'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 535, in get
        yield self.spawn_single_user(current_user)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.5/dist-packages/sudospawner/spawner.py", line 90, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/spawner.py", line 770, in get_env
        env = self.user_env(env)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/spawner.py", line 757, in user_env
        home = pwd.getpwnam(self.user.name).pw_dir
    KeyError: 'getpwnam(): name not found: myGithubAccount'

[E 2017-05-02 17:39:54.894 JupyterHub log:99] {
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "X-Forwarded-Port": "1080",
      "X-Forwarded-Proto": "https",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36",
      "Connection": "close",
      "Accept-Language": "en-US,en;q=0.8",
      "Host": "<my domain>",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "X-Forwarded-For": "::ffff:<my addr>",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Referer": "https://<my domain>/hub/home",
      "Cookie": "jupyter-hub-token=\""<my token>",
      "X-Forwarded-Host": "<my domain>"
    }
[E 2017-05-02 17:39:54.895 JupyterHub log:100] 500 GET /hub/user/myGithubAccount (myGithubAccount@::ffff:<my addr>) 57.89ms
```
Here is my `pip freeze`:

```
alembic (0.9.1)
beautifulsoup4 (4.4.1)
bleach (2.0.0)
chardet (2.3.0)
command-not-found (0.3)
decorator (4.0.11)
defer (1.0.6)
docker-py (1.10.6)
docker-pycreds (0.2.1)
dockerspawner (0.7.0)
entrypoints (0.2.2)
escapism (0.0.1)
html5lib (0.999999999)
ipykernel (4.6.1)
ipython (6.0.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
jupyterhub (0.7.2)
language-selector (0.1)
lxml (3.5.0)
Mako (1.0.6)
MarkupSafe (1.0)
mistune (0.7.4)
nbconvert (5.1.1)
nbformat (4.3.0)
nltk (3.2.2)
notebook (5.0.0)
oauthenticator (0.5.1)
pamela (0.3.0)
pandocfilters (1.4.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.14)
ptyprocess (0.5.1)
pycups (1.9.73)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-editor (1.0.3)
python-systemd (231)
pyxdg (0.25)
pyzmq (16.0.2)
qtconsole (4.3.0)
requests (2.9.1)
screen-resolution-extra (0.0.0)
setuptools (28.0.0)
simplegeneric (0.8.1)
six (1.10.0)
SQLAlchemy (1.1.9)
ssh-import-id (5.5)
sudospawner (0.4.0)
system-service (0.3)
terminado (0.6)
testpath (0.3)
tornado (4.5.1)
traitlets (4.3.2)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
virtualenv (15.0.1)
wcwidth (0.1.7)
webencodings (0.5.1)
websocket-client (0.40.0)
wheel (0.29.0)
widgetsnbextension (2.0.0)
xkit (0.0.0)
```

**Comment by minrk** [comment]
@hayjoss and can you include the logs starting from JupyterHub launch? You may want to remove `jupyterhub.sqlite` to start fresh.

**Comment by hayjoss** [comment]
Here is the boot-up log:

```
[I 2017-05-03 07:32:55.468 JupyterHub app:1332] Cleaning up single-user servers...
[I 2017-05-03 07:32:55.539 JupyterHub app:1343] Cleaning up proxy[10653]...
[I 2017-05-03 07:32:55.540 JupyterHub app:1369] ...done
<my system user>@remeshdl:~$ jupyterhub
[I 2017-05-03 09:49:09.436 JupyterHub app:724] Loading cookie_secret from /home/<my system user>/jupyterhub_cookie_secret
[W 2017-05-03 09:49:09.458 JupyterHub app:365] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ef7908>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ef7940>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ee7940>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ef7e10>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ee9be0>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925f090b8>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925f091d0>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925f09518>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
[I 2017-05-03 09:49:09.491 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[I 2017-05-03 09:49:09.493 JupyterHub app:1176] Starting proxy @ http://*:1080/
09:49:09.601 - info: [ConfigProxy] Proxying https://*:1080 to http://127.0.0.1:8081
09:49:09.604 - info: [ConfigProxy] Proxy API at http://127.0.0.1:1081/api/routes
[I 2017-05-03 09:49:09.699 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:1080/
```
Will try removing the sqlite!

**Comment by hayjoss** [comment]
Here is the boot up log:

```
[I 2017-05-03 07:32:55.468 JupyterHub app:1332] Cleaning up single-user servers...
[I 2017-05-03 07:32:55.539 JupyterHub app:1343] Cleaning up proxy[10653]...
[I 2017-05-03 07:32:55.540 JupyterHub app:1369] ...done
<my system user>@<my host>:~$ jupyterhub
[I 2017-05-03 09:49:09.436 JupyterHub app:724] Loading cookie_secret from /home/<my system user>/jupyterhub_cookie_secret
[W 2017-05-03 09:49:09.458 JupyterHub app:365] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ef7908>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ef7940>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ee7940>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ef7e10>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925ee9be0>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925f090b8>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925f091d0>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
{'value': 'notebooks/', 'owner': <sudospawner.spawner.SudoSpawner object at 0x7f5925f09518>, 'trait': <traitlets.traitlets.Unicode object at 0x7f5923b94ef0>}
[I 2017-05-03 09:49:09.491 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[I 2017-05-03 09:49:09.493 JupyterHub app:1176] Starting proxy @ http://*:1080/
09:49:09.601 - info: [ConfigProxy] Proxying https://*:1080 to http://127.0.0.1:8081
09:49:09.604 - info: [ConfigProxy] Proxy API at http://127.0.0.1:1081/api/routes
[I 2017-05-03 09:49:09.699 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:1080/
```

Will try removing the sqlite file.

**Comment by hayjoss** [comment]
I can't really quite pin down what happened, but I know for sure that the first time I authed in, my personal github user created it's own homedir with this config (I'm almost 100% certain of that - I suppose I could've tweaked something). But now when new people are signing in I get the 500 error and no directories are being created etc.

**Comment by hayjoss** [comment]
So basically to get this working with the config above, I just referenced:
https://github.com/jupyterhub/oauthenticator/blob/master/example/addusers.sh

Since I know who my users are I was able to simply add them via:
`sudo useradd -m -s /bin/bash $user`

I had to add their `notebooks` folder inside there as well as `chown` the dir properly. But at least now people can log in.
