### ISSUE TITLE
Can't open login page

### ISSUE THREAD

**Issue by geekraver** [jupyter/jupyterhub#473]
I'm seeing this:

      discarding /home/gram/anaconda/bin from PATH
      prepending /home/gram/anaconda/envs/py35/bin to PATH
      [I 2016-03-08 22:11:01.373 JupyterHub app:523] Loading cookie_secret from /home/gram/notebooks/jupyterhub_cookie_secret
      [W 2016-03-08 22:11:01.397 JupyterHub app:258] 
          Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
          Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
          
      [W 2016-03-08 22:11:01.401 JupyterHub app:642] No admin users, admin interface will be unavailable.
      [W 2016-03-08 22:11:01.401 JupyterHub app:643] Add any administrative users to `c.Authenticator.admin_users` in config.
      [I 2016-03-08 22:11:01.401 JupyterHub app:669] Not using whitelist. Any authenticated user will be allowed.
      [I 2016-03-08 22:11:01.414 JupyterHub app:1052] Hub API listening on http://localhost:8081/hub/
      [I 2016-03-08 22:11:01.417 JupyterHub app:803] Starting proxy @ http://*:8000/
      22:11:01.500 - info: [ConfigProxy] Proxying https://*:8000 to http://localhost:8081
      22:11:01.501 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
      [I 2016-03-08 22:11:01.522 JupyterHub app:1075] JupyterHub is now running at http://localhost:8000/
      [E 2016-03-08 22:11:12.040 JupyterHub web:1524] Uncaught exception GET /hub/login (192.168.2.2)
          HTTPServerRequest(protocol='https', host='192.168.2.10:8000', method='GET', uri='/hub/login', version='HTTP/1.1', remote_ip='192.168.2.2', headers={'X-Forwarded-Proto': 'https', 'Host': '192.168.2.10:8000', 'Accept-Language': 'en-US,en;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36', 'Connection': 'close', 'X-Forwarded-Port': '8000', 'Cookie': 'gsScrollPos=0', 'X-Forwarded-For': '192.168.2.2', 'Cache-Control': 'max-age=0', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Accept-Encoding': 'gzip, deflate, sdch'})
          Traceback (most recent call last):
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/tornado/web.py", line 1443, in _execute
              result = method(*self.path_args, **self.path_kwargs)
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 55, in get
              self.finish(self._render(username=username))
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/login.py", line 34, in _render
              login_url=self.settings['login_url'],
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 367, in render_template
              template = self.get_template(name)
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 363, in get_template
              return self.settings['jinja2_env'].get_template(name)
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
              return self._load_template(name, self.make_globals(globals))
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 774, in _load_template
              cache_key = self.loader.get_source(self, name)[1]
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jinja2/loaders.py", line 187, in get_source
              raise TemplateNotFound(template)
          jinja2.exceptions.TemplateNotFound: login.html
          
      [E 2016-03-08 22:11:12.041 JupyterHub web:976] Uncaught exception in write_error
          Traceback (most recent call last):
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/tornado/web.py", line 974, in send_error
              self.write_error(status_code, **kwargs)
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 416, in write_error
              html = self.render_template('error.html', **ns)
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 367, in render_template
              template = self.get_template(name)
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 363, in get_template
              return self.settings['jinja2_env'].get_template(name)
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
              return self._load_template(name, self.make_globals(globals))
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jinja2/environment.py", line 774, in _load_template
              cache_key = self.loader.get_source(self, name)[1]
            File "/home/gram/anaconda/envs/py35/lib/python3.5/site-packages/jinja2/loaders.py", line 187, in get_source
              raise TemplateNotFound(template)
          jinja2.exceptions.TemplateNotFound: error.html
          
      [E 2016-03-08 22:11:12.046 JupyterHub log:99] {
            "X-Forwarded-Proto": "https",
            "Host": "192.168.2.10:8000",
            "Accept-Language": "en-US,en;q=0.8",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36",
            "Connection": "close",
            "X-Forwarded-Port": "8000",
            "Cookie": "gsScrollPos=0",
            "X-Forwarded-For": "192.168.2.2",
            "Cache-Control": "max-age=0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
            "Upgrade-Insecure-Requests": "1",
            "Accept-Encoding": "gzip, deflate, sdch"
          }
      [E 2016-03-08 22:11:12.046 JupyterHub log:100] 500 GET /hub/login (@192.168.2.2) 3.42ms

      Interrupted
      [I 2016-03-08 22:11:18.799 JupyterHub app:944] Cleaning up single-user servers...
      [I 2016-03-08 22:11:18.840 JupyterHub app:955] Cleaning up proxy[18949]...
      [I 2016-03-08 22:11:18.841 JupyterHub app:981] ...done

**Comment by minrk** [comment]
How did you install JupyterHub?

**Comment by geekraver** [comment]
Looking at my bash history to try reconstruct this. This was based off the README:

sudo apt-get install npm nodejs-legacy
sudo npm install -g configurable-http-proxy
conda create -name py35 pip python=3
source activate py35
pip install jupyterhub

Then I create a self-signed cert and edited jupyterhub_config.py to reference that and the key.

Then I just run jupyterhub.

Python version is 3.5.1

**Comment by minrk** [comment]
That certainly looks right! What do you see in `/home/gram/anaconda/envs/py35/share/jupyter`?

You could try reinstalling:

    pip uninstall jupyterhub
    pip install jupyterhub

**Comment by willingc** [comment]
@geekraver @minrk In addition to Min's suggestion, I would recommend removing pip from this line and see if that helps:
``conda create -name py35 pip python=3``

**Comment by geekraver** [comment]
Ah, figured it out! I had misunderstood the data_files_path setting and had pointed that to the directory I want notebooks to be stored.

**Comment by ynnelson** [comment]
@ghost Would you mind elaborating and explain what you misunderstood, I am getting the same error and can't figure it out for the life of me...

**Comment by yourinoelnelson** [comment]
NVM figured it out!!

**Comment by ynnelson** [comment]
NVM I figured it out! :)
