### ISSUE TITLE
Docker image missing Jupyter

### ISSUE THREAD

**Issue by nevdullcode** [jupyter/jupyterhub#475]
I ran the following:

```bash
docker pull jupyter/jupyterhub
docker run -d --name jhub -p 8000:8000 jupyter/jupyterhub jupyterhub --no-ssl
docker exec -it jhub bash #To eventually configure users/passwords
```

After adding a user and setting the user's password I attempted to log in via the JupyterHub UI.

The UI shows the following error message:

```
500 : Internal Server Error
Spawner failed to start [status=1]
```

I see this in the log:

```
[I 2016-03-09 23:08:15.661 JupyterHub spawner:436] Spawning jupyterhub-singleuser --user=denton --port=52848 --cookie-name=jupyter-hub-token-denton --base-url=/user/denton --hub-host= --hub-prefix=/hub/ --hub-api-url=http://127.0.0.1:8081/hub/api --ip=127.0.0.1
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 21, in <module>
    import notebook
ImportError: No module named 'notebook'
2016-03-09T23:08:15.884289173Z 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 23, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
[W 2016-03-09 23:08:25.686 JupyterHub web:1521] 500 POST /hub/login?next= (192.168.99.1): Spawner failed to start [status=1]
[E 2016-03-09 23:08:25.698 JupyterHub log:99] {
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.8",
      "Origin": "http://192.168.99.100:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-For": "192.168.99.1",
      "Host": "192.168.99.100:8000",
      "Content-Type": "application/x-www-form-urlencoded",
      "Cache-Control": "max-age=0",
      "Connection": "close",
      "Content-Length": "29",
      "X-Forwarded-Port": "8000",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Referer": "http://192.168.99.100:8000/hub/login"
    }
[E 2016-03-09 23:08:25.698 JupyterHub log:100] 500 POST /hub/login?next= (@192.168.99.1) 10425.97ms
[W 2016-03-09 23:08:45.778 JupyterHub user:262] denton's server never showed up at http://127.0.0.1:52848/user/denton after 30 seconds. Giving up
[E 2016-03-09 23:08:45.791 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7fc2554897b8> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 278, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 254, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 108, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/utils.py", line 94, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://127.0.0.1:52848/user/denton didn't respond in 30 seconds
```

These are the installed pip packages (Jupyter is missing!):

```
# pip list
conda (4.0.1)
conda-env (2.4.5)
decorator (4.0.9)
ipython-genutils (0.1.0)
Jinja2 (2.8)
jupyterhub (0.6.0.dev0)
MarkupSafe (0.23)
pamela (0.2.1)
pip (8.1.0)
pycosat (0.6.1)
PyYAML (3.11)
requests (2.9.1)
setuptools (20.2.2)
SQLAlchemy (1.0.12)
tornado (4.3)
traitlets (4.1.0)
wheel (0.29.0)
```

Running ```pip install jupyter``` inside the container appears to resolve error.

Jupyter should come embeded in the jupyter/jupyterhub Docker image, correct? Thanks!

**Comment by minrk** [comment]
The `jupyter/jupyterhub` image is only an image for running the Hub service itself. It does not require the other Jupyter components, which are needed by the single-user servers.

**Comment by nevdullcode** [comment]
Thanks for the response. Maybe mention that in the Docker related portion of the README.md file in case other users encounter the same issue.

**Comment by willingc** [comment]
@nevdullcode I've gone ahead and taken your suggestion to clarify the README. Thanks!

**Comment by nevdullcode** [comment]
@willingc @minrk Thank you both for the clarification!

**Comment by willingc** [comment]
@nevdullcode :sunny:
